import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';

export async function runAiCombined(sql,container,database) {
 assert.equal(container,'avantia-ai-combined-20260915');
 const request='00000000-0000-4000-8000-000000000120';
 const item='00000000-0000-4000-8000-000000000121';
 const actor='00000000-0000-4000-8000-000000000002';
 const lease='00000000-0000-4000-8000-000000000123';
 const role=`set request.jwt.claims='{"role":"service_role"}';`;
 sql(`insert into quote_requests(id,project_id,owner_id,title) values('${request}','00000000-0000-4000-8000-000000000010','00000000-0000-4000-8000-000000000001','AI synthetic concurrency');
 insert into quote_request_items(id,request_id,project_id,owner_id,name,department,item_type,quantity,unit) values('${item}','${request}','00000000-0000-4000-8000-000000000010','00000000-0000-4000-8000-000000000001','Original preserved','General','material',1,'each');
 insert into client_material_list_jobs(request_id,status,generation,ai_chunk_lease) values('${request}','processing',1,'${lease}');`);
 const job=sql(`select id from client_material_list_jobs where request_id='${request}'`);
 const checkpoint=`select material_list_checkpoint(${job},1,'${lease}',repeat('c',64),1,0,'{"result":{"items":[]}}');`;
 sql(role+checkpoint);
 const publication=`select publish_material_list_checkpoint(${job},1,'${lease}',repeat('c',64),'[]','synthetic','needs_review');`;
 function query(text,onData) {
  return new Promise((resolve,reject)=>{
   const p=spawn('docker',['exec','-i',container,'psql','-X','-U','postgres','-d',database,'-At','-v','ON_ERROR_STOP=1','-v','VERBOSITY=verbose']);
   let output='';p.stdout.on('data',d=>{output+=d;onData?.(String(d));});p.stderr.on('data',d=>output+=d);
   p.on('error',reject);p.on('close',code=>resolve({code,output}));p.stdin.end(role+`set statement_timeout='8s';set deadlock_timeout='300ms';`+text);
  });
 }
 const edit=`select staff_apply_request_item_edit('${request}','${item}','${actor}',gen_random_uuid(),(select jsonb_build_object('name',name,'department',department,'quantity',quantity,'unit',unit,'metadata',metadata,'qualification_status',qualification_status) from quote_request_items where id='${item}'),null,null,'{"name":"Edit preserved"}');`;
 let unlock;
 const locked=new Promise(resolve=>unlock=resolve);
 const first=query(`begin;${edit}select 'EDIT_LOCKED';select pg_sleep(1);commit;`,t=>{if(t.includes('EDIT_LOCKED'))unlock();});
 await locked;
 const second=query(publication);
 assert.equal((await first).code,0);
 const stale=await second;assert.notEqual(stale.code,0);assert.match(stale.output,/stale_job/);
 assert.equal(sql(`select name from quote_request_items where id='${item}'`),'Edit preserved');
 console.log('PASS combined edit-first: actual source-edit RPC wins; stale publication rejected unchanged.');
 sql(`update client_material_list_jobs set generation=1,status='processing',ai_chunk_lease='${lease}' where id=${job};delete from private.client_material_list_checkpoints where job_id=${job};`);
 sql(role+checkpoint);
 let start;
 const started=new Promise(resolve=>start=resolve);
 const publisher=query(`begin;select id from client_material_list_jobs where id=${job} for update;select 'JOB_LOCKED';select pg_sleep(1);${publication}commit;`,t=>{if(t.includes('JOB_LOCKED'))start();});
 await started;
 const editor=query(edit.replace('Edit preserved','Second edit preserved'));
 const result=await Promise.all([publisher,editor]);
 console.log('Publication-first outcomes:',JSON.stringify(result));
 assert.ok(!result.some(r=>/deadlock detected/.test(r.output)),'BLOCKER: publication-first and real source-edit RPC deadlock in combined schema');
 assert.equal(result[0].code,0,'publisher owning job first should finish');
 assert.match(result[1].output,/55P03/,'contending edit must receive safe retry');
 assert.equal(sql(`select name from quote_request_items where id='${item}'`),'Edit preserved','failed edit must not mutate source');
 assert.equal(sql(`select generation from client_material_list_jobs where id=${job}`),'1','failed edit must not invalidate generation');
 assert.equal(sql(`select results ? '0' and published_at is not null from private.client_material_list_checkpoints where job_id=${job}`),'t','completed checkpoint lost');
 const retry=await query(edit.replace('Edit preserved','Second edit preserved'));
 assert.equal(retry.code,0,retry.output);
 assert.equal(sql(`select name from quote_request_items where id='${item}'`),'Second edit preserved');
 assert.equal(sql(`select generation from client_material_list_jobs where id=${job}`),'2');
 console.log('PASS combined publication-first: 55P03 edit rollback, checkpoint retained, explicit edit retry succeeds.');
 const attachment=`insert into quote_request_attachments(request_id,project_id,owner_id,file_name,file_path,source_party) values('${request}','00000000-0000-4000-8000-000000000010','00000000-0000-4000-8000-000000000001','synthetic.pdf','synthetic/ai-lock.pdf','client');`;
 function resetCheckpoint() {
  sql(`update client_material_list_jobs set generation=1,status='processing',ai_chunk_lease='${lease}' where id=${job};delete from private.client_material_list_checkpoints where job_id=${job};`);
  sql(role+checkpoint);
 }
 resetCheckpoint();
 let fileLocked;
 const fileReady=new Promise(resolve=>fileLocked=resolve);
 const fileFirst=query(`begin;${attachment}select 'FILE_LOCKED';select pg_sleep(1);commit;`,t=>{if(t.includes('FILE_LOCKED'))fileLocked();});
 await fileReady;
 const afterFile=query(publication);
 assert.equal((await fileFirst).code,0);
 assert.match((await afterFile).output,/stale_job/);
 assert.equal(sql(`select count(*) from quote_request_attachments where request_id='${request}'`),'1');
 resetCheckpoint();
 let fileStart;
 const fileStarted=new Promise(resolve=>fileStart=resolve);
 const beforeFile=query(`begin;select id from client_material_list_jobs where id=${job} for update;select 'JOB_LOCKED';select pg_sleep(1);${publication}commit;`,t=>{if(t.includes('JOB_LOCKED'))fileStart();});
 await fileStarted;
 const fileSecond=query(attachment.replace('ai-lock.pdf','ai-lock-second.pdf'));
 const fileOutcomes=await Promise.all([beforeFile,fileSecond]);
 assert.equal(fileOutcomes[0].code,0,fileOutcomes[0].output);
 assert.match(fileOutcomes[1].output,/55P03/);
 assert.equal(sql(`select count(*) from quote_request_attachments where request_id='${request}'`),'1','failed attachment leaked a row');
 assert.equal(sql(`select generation from client_material_list_jobs where id=${job}`),'1');
 assert.equal((await query(attachment.replace('ai-lock.pdf','ai-lock-second.pdf'))).code,0);
 assert.equal(sql(`select count(*) from quote_request_attachments where request_id='${request}'`),'2');
 console.log('PASS both attachment/publication orders: source fence rollback, stale rejection, safe retry.');
 sql(`insert into quote_request_items(request_id,project_id,owner_id,name,department,item_type,quantity,unit,metadata) values('${request}','00000000-0000-4000-8000-000000000010','00000000-0000-4000-8000-000000000001','Existing reviewed synthetic product','General','material',1,'each','{"ai_organized":true,"manually_reviewed_at":"2026-09-15"}');`);
 resetCheckpoint();
 sql(`delete from private.client_material_list_checkpoints where job_id=${job};`);
 const finish=`select finish_material_list_checkpoint_job(${job},1,'${lease}',true,'already_organized',1,0,null);`;
 assert.match(sql(role+finish),/completed/,'nonforced existing list should finish without provider/checkpoint');
 assert.equal(sql(`select count(*) from private.client_material_list_checkpoints where job_id=${job}`),'0');
 sql(`update client_material_list_jobs set status='processing',generation=1,ai_chunk_lease='${lease}',force_requested=true where id=${job};`);
 assert.match((await query(finish)).output,/checkpoint_not_published/,'force must not bypass checkpoint');
 assert.equal(sql(`select count(*) from quote_request_items where request_id='${request}' and metadata ? 'manually_reviewed_at'`),'1');
 console.log('PASS already-organized no-op finalization; forced attempt cannot forge publication.');
}
