import { readFile } from "node:fs/promises"
import path from "node:path"

import { expect, test } from "@playwright/test"

const root = process.cwd()

test("manager navigation is compact and keeps communication shortcuts at the bottom", async () => {
  const [shell, aiTools] = await Promise.all([
    readFile(path.join(root, "components/buildflow/admin-shell.tsx"), "utf8"),
    readFile(path.join(root, "app/admin/ai-tools/page.tsx"), "utf8"),
  ])
  expect(shell).toContain('label: "Material Catalog"')
  expect(shell).toContain('href: "/admin/catalog"')
  expect(shell).not.toContain('label: "Website Traffic"')
  expect(shell).toContain('label: "AI Tools — Coming Soon"')
  expect(shell).toContain("Manager Dashboard")
  expect(shell).toContain('label: "Messages and calls"')
  expect(shell).not.toContain('label: "Directories & Catalog"')
  expect(shell).not.toContain('label: "Supplier Pricing"')
  expect(shell).not.toContain('href: "/admin/abc"')
  expect(aiTools).toContain('href: "/admin/abc"')
  expect(aiTools).toContain('href: "/admin/traffic"')
  expect(shell).toContain('href: "/admin/payments"')
  expect(shell).not.toContain('label: "Manager Settings"')
  expect(shell).toContain("Go to Customer Website")
  expect(shell).toContain("Quick Access")
  expect(shell).not.toContain('<span className="min-w-0 flex-1 text-left">More</span>')
  expect(shell).toContain('shortLabel: "Messages"')
  expect(shell).toContain('shortLabel: "Meet"')
  expect(shell).toContain('shortLabel: "WhatsApp"')
  expect(shell).toContain('const GOOGLE_MEET_URL = "https://meet.google.com/"')
  expect(shell).toContain('/admin/communications?channel=whatsapp')
  expect(shell.lastIndexOf("communicationLinks.map")).toBeGreaterThan(shell.indexOf("</nav>"))
})

test("manager catalog is protected, seeded, editable, and supplier based", async () => {
  const [page, workspace, actions, migration, specificationMigration, retailSupplierMigration, exactLinkMigration, snapshotMigration, homeDepotSnapshot, allDepartmentRetailers, verifiedRetailProducts, curatedProducts, qualityMigration, coreCurationMigration, qualityHelpers, parser] = await Promise.all([
    readFile(path.join(root, "app/admin/catalog/page.tsx"), "utf8"),
    readFile(path.join(root, "components/buildflow/material-catalog-workspace.tsx"), "utf8"),
    readFile(path.join(root, "app/admin/catalog/actions.ts"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260814033000_create_manager_material_catalog.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260814155841_add_catalog_measurements_and_common_items.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260814160945_add_retail_catalog_suppliers.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260814162242_add_verified_retail_product_links.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260816190156_add_catalog_retail_snapshot_metadata.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260816193227_seed_home_depot_framing_snapshot.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260816203816_ensure_retailers_in_every_catalog_department.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260816210019_seed_verified_retail_catalog_products.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260816223000_curate_common_catalog_products.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260817001500_add_catalog_quality_and_price_history.sql"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260817013000_curate_core_catalog_materials.sql"), "utf8"),
    readFile(path.join(root, "lib/material-catalog-quality.ts"), "utf8"),
    readFile(path.join(root, "lib/material-catalog-pdf.ts"), "utf8"),
  ])
  expect(page).toContain("requireManagerPortalProfile")
  expect(page).toContain('rpc("staff_load_catalog_suppliers")')
  expect(workspace).toContain("Materials & supplier pricing")
  expect(workspace).toContain("Import PDF")
  expect(workspace).toContain("Add supplier")
  expect(workspace).toContain("Catalog suppliers")
  expect(workspace).toContain("Filter suppliers by department")
  expect(workspace).toContain("Suppliers are filtered by the departments selected in Supplier Settings")
  expect(workspace).toContain("supplierServesMaterialDepartment(supplier, catalogSupplierDepartment)")
  expect(workspace).toContain("Only suppliers you add become price columns")
  expect(workspace).toContain("saveCatalogDepartmentSuppliersAction")
  expect(workspace).toContain("catalogSupplierIds[selectedCategory]")
  expect(workspace).toContain("not_available")
  expect(workspace).toContain("Save item")
  expect(workspace).toContain("Measurement / size")
  expect(workspace).toContain("Thickness / gauge")
  expect(workspace).toContain("Open exact ${item.name} at ${supplier.name}")
  expect(workspace).toContain("Add exact ${supplier.name} product link for ${item.name}")
  expect(workspace).not.toContain("https://www.lowes.com/search?searchTerm=")
  expect(workspace).not.toContain("https://www.homedepot.com/s/")
  expect(workspace).toContain("itemColumnWidth")
  expect(workspace).toContain("priceColumnWidth")
  expect(workspace).toContain("Item column")
  expect(workspace).toContain("Price column")
  expect(workspace).toContain("avantia-catalog-item-column-width")
  expect(workspace).toContain("avantia-catalog-price-column-width")
  expect(workspace).toContain("Retail pricing location: ZIP 11516")
  expect(workspace).toContain("Missing price")
  expect(workspace).toContain("Needs review")
  expect(workspace).toContain("Catalog confidence")
  expect(workspace).toContain("hideSupplier")
  expect(workspace).toContain("Hide from {selectedCategory}")
  expect(workspace).toContain("You can restore it with Add supplier")
  expect(workspace).toContain("Package quantity")
  expect(workspace).toContain("Manufacturer model")
  expect(workspace).toContain("Price details")
  expect(workspace).not.toContain("Valley Stream #1216")
  expect(workspace).not.toContain("snapshotLabel")
  expect(workspace).not.toContain('<option value="unknown">Unknown</option><option value="available">Available</option><option value="not_available">N/A</option></select>\n                      {draft.productUrl')
  expect(workspace).toContain('supplier.id === "home-depot-retail-catalog"')
  expect(actions).toContain("Use an exact ${supplier.name} product page")
  expect(actions).toContain('url.pathname.startsWith("/pd/")')
  expect(actions).toContain('url.pathname.startsWith("/p/")')
  expect(actions).toContain('storeId: "1216"')
  expect(actions).toContain('zipCode: "11516"')
  expect(actions).toContain("LOWES_SNAPSHOT")
  expect(actions).toContain("isRetailSnapshot")
  expect(page).toContain("product_url")
  expect(workspace).not.toContain("Sample quantity")
  expect(workspace).toContain("price per {item.unit}")
  expect(actions).toContain("extractMaterialCatalogItemsFromPdf")
  expect(actions).toContain("deleteMaterialCatalogItemAction")
  expect(actions).toContain('review_status: "discontinued"')
  expect(actions).not.toContain('.delete({ count: "exact" })')
  expect(actions).toContain("catalogEnabledDepartments")
  expect(actions).toContain("measurement: clean(input.measurement")
  expect(actions).toContain("thickness: clean(input.thickness")
  expect(actions).toContain('requireStaffProfile("suppliers")')
  expect(actions).toContain("supplierIsAddedToCatalogDepartment(supplier, department)")
  expect(migration).toContain("create table if not exists public.material_catalog_items")
  expect(migration).toContain("create table if not exists public.material_catalog_supplier_prices")
  expect(migration).toContain("private.is_admin_or_staff()")
  expect(migration).toContain("on delete cascade")
  expect(migration.match(/'Simple Material Comparison PDF'/g)?.length).toBe(103)
  expect(specificationMigration).toContain("add column if not exists measurement")
  expect(specificationMigration).toContain("add column if not exists thickness")
  expect(specificationMigration).toContain("FRA-020")
  expect(specificationMigration).toContain("ELE-020")
  expect(specificationMigration).not.toContain("delete from public.material_catalog_items")
  expect(retailSupplierMigration).toContain("lowes-retail-catalog")
  expect(retailSupplierMigration).toContain("home-depot-retail-catalog")
  expect(retailSupplierMigration).toContain("https://www.lowes.com/")
  expect(retailSupplierMigration).toContain("https://www.homedepot.com/")
  expect(exactLinkMigration).toContain("add column if not exists product_url")
  expect(exactLinkMigration).toContain("Search and category URLs are not allowed")
  expect(snapshotMigration).toContain("price_observed_at")
  expect(snapshotMigration).toContain("retail_store_id")
  expect(homeDepotSnapshot).toContain("FRA-001")
  expect(homeDepotSnapshot).toContain("https://www.homedepot.com/p/314732316")
  expect(homeDepotSnapshot).toContain("Confirm local stock and checkout price")
  expect(allDepartmentRetailers).toContain("home-depot-retail-catalog")
  expect(allDepartmentRetailers).toContain("lowes-retail-catalog")
  expect(allDepartmentRetailers).toContain('"Others"')
  expect(verifiedRetailProducts).toContain("/images/materials/catalog/win-004.jpg")
  expect(verifiedRetailProducts).toContain("36 x 60 in. double-hung window")
  expect(verifiedRetailProducts).toContain("6-mil polyethylene vapor barrier, 10 x 100 ft.")
  expect(verifiedRetailProducts).not.toMatch(/\/(questions|reviews|sets)\//)
  expect(curatedProducts).toContain("retailer prices verified on exact product pages")
  expect(curatedProducts).toContain("'11516'")
  expect(curatedProducts).toContain("7/16-in. x 4-ft. x 8-ft. OSB roof sheathing")
  expect(curatedProducts).toContain("unit = 'bags'")
  expect(qualityMigration).toContain("material_catalog_price_history")
  expect(qualityMigration).toContain("archive_material_catalog_price_trigger")
  expect(qualityMigration).toContain("GAF Timberline HDZ Charcoal")
  expect(qualityMigration).not.toContain("delete from public.material_catalog_items")
  expect(coreCurationMigration).toContain("Lightweight joint compound - blue lid")
  expect(coreCurationMigration).toContain("1/2 in. regular drywall, 4 x 8 ft.")
  expect(coreCurationMigration).toContain("5/8 in. CDX plywood sheathing, 4 x 8 ft.")
  expect(coreCurationMigration).toContain("flat flush hollow-core slab door")
  expect(coreCurationMigration).not.toContain("delete from public.material_catalog_items")
  expect(qualityHelpers).toContain("catalogItemMatchesReview")
  expect(qualityHelpers).toContain("normalizedComparisonPrice")
  expect(qualityHelpers).toContain("priceCheckedDateLabel")
  expect(workspace).toContain("priceCheckedDateLabel(saved)")
  expect(parser).toContain("parseMaterialComparisonText")
  expect(parser).toContain("No quantity, unit, and material rows were found")
})

test("Sheet Rock uses compact configurable products and expandable images", async ({ page }) => {
  await page.goto("/shop/sheet-rock")
  await expect(page.getByRole("heading", { name: "Sheet rock", exact: true })).toBeVisible()
  await expect(page.getByRole("heading", { name: /drywall board/i })).toBeVisible()
  await expect(page.getByRole("button", { name: "Enlarge product image" })).toBeVisible()
  await expect(page.getByText("Quantity", { exact: true })).toBeVisible()
  await expect(page.getByRole("group", { name: "Drywall sheet quantity" })).toBeVisible()
  await expect(page.getByText("Edge profile", { exact: true })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Ceiling", exact: true })).toHaveCount(0)
  await expect(page.getByText("Add the matching materials", { exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: /Add configured item/i })).toBeVisible()
})

test("request estimate PDF has the branded estimate structure and does not persist ACH values", async () => {
  const [panel, actions, pdf] = await Promise.all([
    readFile(path.join(root, "components/buildflow/request-management-panel.tsx"), "utf8"),
    readFile(path.join(root, "app/owner/materials/requests/actions.ts"), "utf8"),
    readFile(path.join(root, "lib/request-client-quote-pdf.ts"), "utf8"),
  ])
  expect(panel).toContain("Create client quote")
  expect(panel).toContain("Include ACH payment information")
  expect(panel).toContain('type="password"')
  expect(panel).toContain("These values are used only to create this PDF and are not saved")
  expect(actions).toContain('client_action: "estimate_sent"')
  expect(actions).not.toContain("routing_number:")
  expect(actions).not.toContain("account_number:")
  expect(pdf).toContain('"ESTIMATE"')
  expect(pdf).toContain('"Item"')
  expect(pdf).toContain('"Description"')
  expect(pdf).toContain('"Quantity"')
  expect(pdf).toContain('"Unit price"')
  expect(pdf).toContain('"Terms & conditions"')
  expect(pdf).toContain('"ACH payment information"')
})
