import { test,expect } from "@playwright/test"
for(const width of [390,1440]) test(`product-first workflow preserves draft and editing at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:950})
  let posts=0
  await page.route("**/*",route=>{if(route.request().method()==="POST"){if(route.request().headers()["next-action"])posts++;return route.abort()}return route.continue()})
  await page.goto("/preview/quote-comparison")
  const cards=page.getByTestId("product-quote-card")
  await expect(page.getByRole("heading",{name:"Supplier quotes",level:1})).toBeVisible()
  await expect(page.getByTitle("280 Lawrence framing package",{exact:true})).toBeVisible()
  await expect(cards).toHaveCount(3)
  await expect(cards.locator("details[open]")).toHaveCount(0)
  await expect(page.getByText("Temporary choices · not saved · no orders sent",{exact:true}).last()).toBeVisible()
  await expect(page.getByRole("navigation",{name:"Quote comparison steps"})).toHaveCount(0)
  await expect(page.getByRole("button",{name:"Add quote",exact:true})).toBeVisible()
  await expect(page.getByRole("button",{name:"Whole-order routes and client pricing",exact:true})).toHaveCount(0)
  await expect(page.getByLabel("Live temporary product selection totals")).not.toBeVisible()
  await page.screenshot({path:`/tmp/step2-products-closed-${width}.png`,fullPage:true})
  await cards.nth(0).locator("summary").click()
  await cards.nth(0).locator('input[type="radio"]:enabled').first().check()
  await expect(cards.nth(0).locator("summary")).toContainText("Draft ·")
  await cards.nth(1).locator("summary").click()
  await expect(cards.locator("details[open]")).toHaveCount(1)
  await expect(cards.nth(0).locator("details")).not.toHaveAttribute("open","")
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:`/tmp/step2-products-open-${width}.png`,fullPage:true})
  await cards.nth(1).getByRole("button",{name:"Compare details / review matches",exact:true}).click()
  await expect(page.getByRole("button",{name:/Edit prices/}).first()).toHaveAttribute("aria-current","page")
  await page.getByRole("button",{name:/Products/}).first().click()
  await page.getByRole("button",{name:"Add quote",exact:true}).click()
  await expect(page.getByRole("button",{name:/Edit prices/}).first()).toHaveAttribute("aria-current","page")
  await page.reload()
  await expect(cards.nth(0).locator("summary")).not.toContainText("Draft ·")
  await page.getByRole("button",{name:"More",exact:true}).click()
  await expect(page.getByRole("navigation",{name:"Quote comparison steps"})).toBeVisible()
  await expect(page.getByRole("button",{name:"Whole-order routes and client pricing",exact:true})).toBeVisible()
  await expect(page.getByRole("button",{name:"Draft lowest prices",exact:true})).toBeVisible()
  await expect(page.getByLabel("Live temporary product selection totals")).toBeVisible()
  await page.getByRole("button",{name:"Less",exact:true}).click()
  await expect(page.getByRole("navigation",{name:"Quote comparison steps"})).toHaveCount(0)
  expect(posts).toBe(0)
})
