import { readFile } from "node:fs/promises"
import path from "node:path"

import { expect, test } from "@playwright/test"

const root = process.cwd()

test("Manager Tools exposes a private website defect issue inbox", async () => {
  const [tools, page, actions, inbox, migration] = await Promise.all([
    readFile(path.join(root, "app/admin/ai-tools/page.tsx"), "utf8"),
    readFile(path.join(root, "app/admin/ai-tools/website-defects/page.tsx"), "utf8"),
    readFile(path.join(root, "app/admin/ai-tools/website-defects/actions.ts"), "utf8"),
    readFile(path.join(root, "components/buildflow/website-defect-inbox.tsx"), "utf8"),
    readFile(path.join(root, "supabase/migrations/20260903205430_create_website_defects.sql"), "utf8"),
  ])

  expect(tools).toContain('href: "/admin/ai-tools/website-defects"')
  expect(tools).toContain('title: "Website Defects"')
  expect(page).toContain("requireManagerPortalProfile")
  expect(page).toContain("!access.aiTools")
  expect(page).toContain('createSignedUrl(row.file_path')
  expect(actions).toContain("prepareWebsiteDefectUploadAction")
  expect(actions).toContain("completeWebsiteDefectUploadAction")
  expect(actions).toContain("updateWebsiteDefectAction")
  expect(actions).toContain("recordWebsiteQaCheckAction")
  expect(actions).toContain("MAX_FILE_SIZE = 100 * 1024 * 1024")
  expect(actions).toContain('"video/quicktime"')
  expect(actions).toContain("expectedPrefix")
  expect(inbox).toContain("Upload and create issue")
  expect(inbox).toContain("Ready to verify")
  expect(inbox).toContain("Codex review / fix notes")
  expect(inbox).toContain("Required website checks")
  expect(inbox).toContain("Last checked:")
  expect(migration).toContain("alter table public.website_defects enable row level security")
  expect(migration).toContain("public = false")
  expect(migration).toContain("website_defect_files_manager_read")
  expect(migration).toContain("website_defects_manager_update")
  expect(migration).toContain("create table if not exists public.website_qa_checks")
  expect(migration).toContain("Send a message as a client")
  expect(migration).toContain("Create and send a proposal")
})

test("website defect uploads stay private and become numbered trackable issues", async () => {
  const migration = await readFile(path.join(root, "supabase/migrations/20260903205430_create_website_defects.sql"), "utf8")
  expect(migration).toContain("issue_number bigint generated by default as identity unique")
  expect(migration).toContain("'new', 'reviewing', 'fixing', 'ready_to_verify', 'resolved'")
  expect(migration).toContain("file_size between 1 and 104857600")
  expect(migration).toContain("(storage.foldername(name))[1] = (select auth.uid())::text")
  expect(migration).not.toMatch(/to anon[\s\S]*using \(true\)/)
})
