-- Idempotent data sync for concrete customer-facing products.
-- Public selling prices are recorded as notes, not as supplier costs.
insert into public.material_catalog_items (
  category, item_code, name, description, measurement, thickness, brand,
  manufacturer_model_number, package_quantity, package_unit,
  comparison_quantity, comparison_unit, review_status, quality_notes,
  default_quantity, unit, image_url, status, source, sort_order, updated_at
)
values
  ('Appliances', 'APP-001', 'GE 30 in. Free-Standing Gas Range', 'Rental-ready stainless steel gas range with four sealed burners, a 13,000 BTU burner, precise simmer control, a broiler drawer, and a 4.8 cu. ft. oven.', '30 in. W x 46.25 in. H x 28.75 in. D', '', 'GE', 'JGBS30RETSS', 1, 'each', 1, 'each', 'ready', 'Published website price: $574. This is a customer price, not a supplier cost.', 1, 'each', '/images/materials/appliance-rentals/ge-jgbs30retss-front.jpg', 'active', 'Website product catalog', 10, now()),
  ('Appliances', 'APP-002', 'Frigidaire 18.3 Cu. Ft. Top Freezer Refrigerator', 'Rental-ready stainless steel refrigerator with EvenTemp cooling, adjustable glass shelves, humidity-controlled crispers, and reversible doors.', '30 in. W x 66.375 in. H x 30.375 in. D', '', 'Frigidaire', 'FFHT1835VS', 1, 'each', 1, 'each', 'ready', 'Published website price: $624. This is a customer price, not a supplier cost.', 1, 'each', '/images/materials/appliance-rentals/frigidaire-ffht1835vs-front.jpg', 'active', 'Website product catalog', 20, now()),

  ('Cabinets', 'CAB-001', 'White Shaker Kitchen Cabinet Package', 'Builder-ready white shaker cabinet package for plan-based quoting, finish review, hardware coordination, and appliance clearances.', 'Project specific', '', '', '', 1, 'package', 1, 'package', 'needs_review', 'Custom quote product. Confirm cabinet schedule and layout before supplier pricing.', 1, 'package', '/images/materials/products-real/kitchen-cabinets.jpg', 'active', 'Website product catalog', 10, now()),
  ('Cabinets', 'CAB-002', 'European Slab Kitchen Cabinet Package', 'Modern slab cabinet package coordinated from the plan, design specification, finish direction, and appliance schedule.', 'Project specific', '', '', '', 1, 'package', 1, 'package', 'needs_review', 'Custom quote product. Confirm cabinet schedule and layout before supplier pricing.', 1, 'package', '/images/materials/products-real/kitchen-cabinets.jpg', 'active', 'Website product catalog', 20, now()),

  ('Concrete & Masonry', 'CON-001', '1 Yard Sand Bag', 'Clean construction sand for masonry, leveling, and general jobsite use.', '1 cubic yard', '', '', '', 1, 'bag', 1, 'cubic yard', 'ready', 'Published material price: $54. One-yard bag fee: $35. Delivery fee: $250. These are customer prices, not supplier costs.', 1, 'bag', '/images/materials/bulk-bags/one-yard-sand-bag.webp', 'active', 'Website product catalog', 10, now()),
  ('Concrete & Masonry', 'CON-002', '1 Yard Crushed Stone Bag', 'Common crushed stone for drainage, base preparation, and concrete work.', '1 cubic yard', '', '', '', 1, 'bag', 1, 'cubic yard', 'ready', 'Customer pricing is confirmed before delivery. One-yard bag fee and delivery are separate.', 1, 'bag', '/images/materials/bulk-bags/one-yard-crushed-stone-bag.webp', 'active', 'Website product catalog', 20, now()),
  ('Concrete & Masonry', 'CON-003', '1 Yard Mulch Bag', 'Natural brown mulch for planting beds, landscaping, and site finishing.', '1 cubic yard', '', '', '', 1, 'bag', 1, 'cubic yard', 'ready', 'Customer pricing is confirmed before delivery. One-yard bag fee and delivery are separate.', 1, 'bag', '/images/materials/bulk-bags/one-yard-mulch-bag.webp', 'active', 'Website product catalog', 30, now()),
  ('Concrete & Masonry', 'CON-004', 'Heidelberg Materials Lehigh Portland Cement Type I/II', 'Portland cement Type I/II for concrete, mortar beds, and cement-based jobsite mixes.', '94 lb. bag', '', 'Heidelberg Materials Lehigh', 'Type I/II', 1, 'bag', 1, 'bag', 'ready', 'Published website price: $16.45. This is a customer price, not a supplier cost.', 1, 'bag', '/images/materials/products-real/heidelberg-lehigh-portland-cement-type-i-ii-real.jpg', 'active', 'Website product catalog', 40, now()),
  ('Concrete & Masonry', 'CON-005', 'MAPEI Keraflex Plus Gray Thinset', 'Professional-grade gray polymer-modified mortar for tile installation.', '44 lb. bag', '', 'MAPEI', 'Keraflex Plus', 1, 'bag', 1, 'bag', 'ready', 'Published website price: $18. This is a customer price, not a supplier cost.', 1, 'bag', '/images/materials/products-real/mapei-keraflex-plus-gray-44lb-real.jpg', 'active', 'Website product catalog', 50, now()),

  ('Door & Molding', 'DOM-016', 'White Primed 1-Panel Shaker Interior Door', 'Primed white 1-panel Shaker interior door offered as a slab, prehung door, or double-door configuration.', '6 ft. 8 in. height', '1-3/8 in.', '', '', 1, 'door', 1, 'door', 'ready', 'Website reference prices vary by width: slab $131-$141, prehung $180-$196, double door $372-$435. Confirm final quote.', 1, 'door', '/images/materials/catalog/one-panel-shaker-door.webp', 'active', 'Website product catalog', 160, now()),

  ('Framing', 'FRA-030', '2x8 Treated Lumber', 'Pressure-treated lumber for exterior framing, deck bases, and moisture-prone structural areas.', '12 ft. length', '2 x 8 nominal', '', '', 1, 'piece', 1, 'piece', 'ready', 'Published website price: $23.40. This is a customer price, not a supplier cost.', 1, 'piece', '/images/materials/products-real/2x8-treated-lumber.jpg', 'active', 'Website product catalog', 300, now()),
  ('Framing', 'FRA-031', 'LVL Beam', 'Engineered laminated veneer lumber beam for long spans, headers, and high-load framing zones.', '16 ft. length', '1-3/4 x 11-7/8 in.', '', '', 1, 'piece', 1, 'piece', 'ready', 'Published website price: $118.20. This is a customer price, not a supplier cost.', 1, 'piece', '/images/materials/products-real/lvl-beam-header.jpg', 'active', 'Website product catalog', 310, now()),

  ('Tile', 'TIL-015', 'MAPEI UltraFlex 1 White Thinset Tile Mortar', 'White polymer-modified thinset mortar for ceramic and most natural stone on floors and walls.', '50 lb. bag', '', 'MAPEI', 'UltraFlex 1', 1, 'bag', 1, 'bag', 'ready', 'Published website price: $17.98. This is a customer price, not a supplier cost.', 1, 'bag', '/images/materials/products-real/mapei-ultraflex-thinset.jpg', 'active', 'Website product catalog', 150, now()),
  ('Tile', 'TIL-016', 'Yardas Fine Sand', 'Fine aggregate for tile preparation, mud work, leveling mixes, and mortar-bed assemblies.', 'Bag', '', 'Yardas', '', 1, 'bag', 1, 'bag', 'needs_review', 'Published website price: $6.58. Confirm bag weight before supplier comparison.', 1, 'bag', '/images/materials/products-real/yardas-fine-sand.jpg', 'active', 'Website product catalog', 160, now()),
  ('Tile', 'TIL-017', 'Tile Underlayment Paper for Plywood', 'Paper underlayment layer used over plywood below wire mesh or mortar-bed tile assemblies when specified.', 'Roll', '', '', '', 1, 'roll', 1, 'roll', 'needs_review', 'Published website price: $23.99. Confirm roll dimensions before supplier comparison.', 1, 'roll', '/images/materials/products-real/tile-underlayment-paper.jpg', 'active', 'Website product catalog', 170, now()),
  ('Tile', 'TIL-018', 'Tile Wire Mesh for Mortar Bed', 'Wire-mesh reinforcement for tile preparation and mortar-bed assemblies over prepared plywood.', '27 in. x 96 in.', '', '', '', 1, 'sheet', 1, 'sheet', 'ready', 'Published website price: $21.37. This is a customer price, not a supplier cost.', 1, 'sheet', '/images/materials/products-real/tile-wire-mesh-v2.jpg', 'active', 'Website product catalog', 180, now()),

  ('Siding', 'SID-014', 'Flashing Roll', 'Corrosion-resistant flashing for water management around roofs, walls, and window openings.', '10 in. x 50 ft. roll', '', '', '', 1, 'roll', 1, 'roll', 'ready', 'Published website price: $58.90. This is a customer price, not a supplier cost.', 1, 'roll', '/images/materials/products-real/flashing-roll.jpg', 'active', 'Website product catalog', 140, now()),

  ('Liquidation', 'LIQ-001', '24 in. x 96 in. x 1/2 in. MDF Board - Brand New', 'Brand-new MDF sheets for cabinetry, furniture, shelving, wall panels, and woodworking.', '24 in. x 96 in.', '1/2 in.', '', '', 1, 'board', 1, 'board', 'ready', 'Published website price: $10 per board with a 20-board minimum. Confirm availability and pickup or delivery.', 20, 'board', '/images/liquidation/mdf-board-24x96-half-inch-1.webp', 'active', 'Website product catalog', 10, now()),

  ('Take Care of Yourself', 'TCY-001', 'Noam2 Shabbat Water Bar', 'Countertop water system with four temperature choices and an automatic Shabbat and Yom Tov operating mode.', '17.7 in. H x 12.5 in. W x 14 in. D', '', 'Noam', 'Noam2', 1, 'system', 1, 'system', 'ready', 'Exact product displayed on the customer website.', 1, 'system', '/images/materials/take-care-of-yourself/noam2-water-bar.webp', 'active', 'Website product catalog', 10, now()),
  ('Take Care of Yourself', 'TCY-002', 'AMNON18 Shabbat Hot Water System', 'Automated controller for weekday, Shabbat, and Yom Tov operation of residential hot-water systems.', 'Controller approximately 12 x 12 in.', '', 'AMNON', 'AMNON18', 1, 'system', 1, 'system', 'ready', 'Compatible with electric, gas, oil, indirect, and tankless systems; verify site compatibility.', 1, 'system', '/images/materials/take-care-of-yourself/amnon18-hot-water-system.webp', 'active', 'Website product catalog', 20, now()),
  ('Take Care of Yourself', 'TCY-003', 'Modern House Numbers - Numbers + Letters', 'Made-to-order architectural address numbers and letters for residential, multifamily, and commercial properties.', '4, 6, 8, 12, or 15 in. height', '3/8 in. aluminum', '', '', 1, 'set', 1, 'set', 'ready', 'Custom product; confirm typeface, finish, characters, size, and mounting template.', 1, 'set', '/images/materials/take-care-of-yourself/modern-house-numbers.webp', 'active', 'Website product catalog', 30, now()),
  ('Take Care of Yourself', 'TCY-004', 'Warmboard-S Structural Radiant Panel', 'Structural subfloor and hydronic radiant-heating panel combined into one installation-ready component.', '4 x 8 ft.', '1-1/8 in.', 'Warmboard', 'Warmboard-S', 1, 'panel', 1, 'panel', 'ready', 'Panel uses 1/2-in. tubing at 12-in. spacing; verify system design before ordering.', 1, 'panel', '/images/materials/take-care-of-yourself/warmboard-s-radiant-panel.webp', 'active', 'Website product catalog', 40, now()),
  ('Take Care of Yourself', 'TCY-005', 'KOHLER Invigoration Linear Steam Head K-32309', 'Linear residential steam-shower outlet with an integrated aromatherapy reservoir.', '13-3/4 in. length', '', 'KOHLER', 'K-32309', 1, 'each', 1, 'each', 'ready', 'Requires a compatible generator and controller, sold separately.', 1, 'each', '/images/materials/take-care-of-yourself/kohler-k32309-steam-head.webp', 'active', 'Website product catalog', 50, now()),
  ('Take Care of Yourself', 'TCY-006', 'Tesla Wall Connector', 'Hardwired Level 2 charging station for residential, multifamily, hospitality, or workplace charging.', '24 ft. cable', '', 'Tesla', 'Wall Connector', 1, 'each', 1, 'each', 'ready', 'Maximum 11.5 kW / 48 A on a 60 A circuit; installation requires a qualified electrician.', 1, 'each', '/images/materials/take-care-of-yourself/tesla-wall-connector.webp', 'active', 'Website product catalog', 60, now()),
  ('Take Care of Yourself', 'TCY-007', 'Diode LED BLAZE Wet-Location Niche Lighting System', 'Wet-location LED tape, diffused channel, lens, and correctly sized driver for shower niches and damp architectural details.', '16.4-ft. or 100-ft. tape options', '12 VDC or 24 VDC', 'Diode LED', 'BLAZE', 1, 'system', 1, 'system', 'ready', 'IP65 wet-location system; confirm tape length, color temperature, voltage, channel, and driver load.', 1, 'system', '/images/materials/take-care-of-yourself/diode-led-wet-location-niche-lighting.webp', 'active', 'Website product catalog', 70, now()),
  ('Take Care of Yourself', 'TCY-008', 'Mustee DURABASE 3232M Fiberglass Shower Base', 'Compact one-piece square shower base with a center drain and reinforced molded-fiberglass body.', '32 x 32 in.', '', 'Mustee', '3232M', 1, 'each', 1, 'each', 'ready', 'Center drain connects to 2-in. DWV pipe; verify rough opening and wall system.', 1, 'each', '/images/materials/take-care-of-yourself/mustee-3232m-shower-base.webp', 'active', 'Website product catalog', 80, now()),
  ('Take Care of Yourself', 'TCY-009', 'EverScent Smart Home HVAC Fragrance Diffuser', 'Whole-home scent diffuser that connects to HVAC supply ductwork and distributes fragrance through existing airflow.', 'Coverage up to 5,000 sq. ft.', '3/8-in. delivery tube', 'EverScent', '', 1, 'system', 1, 'system', 'ready', 'Confirm one unit per HVAC system and compatible duct connection.', 1, 'system', '/images/materials/take-care-of-yourself/everscent-hvac-diffuser.webp', 'active', 'Website product catalog', 90, now()),
  ('Take Care of Yourself', 'TCY-010', 'Custom Glass', 'Made-to-order architectural glass and mirror for showers, interiors, storefronts, railings, decorative features, and specialty applications.', 'Custom width x height', 'Custom', '', '', 1, 'piece', 1, 'piece', 'needs_review', 'Confirm product type, dimensions, thickness, quantity, finish, tempering or lamination, edges, holes, notches, cutouts, hardware, and delivery date.', 1, 'piece', '/images/materials/take-care-of-yourself/custom-glass-shower.jpg', 'active', 'Website product catalog', 100, now())
on conflict (item_code) do update set
  category = excluded.category,
  name = excluded.name,
  description = excluded.description,
  measurement = excluded.measurement,
  thickness = excluded.thickness,
  brand = excluded.brand,
  manufacturer_model_number = excluded.manufacturer_model_number,
  package_quantity = excluded.package_quantity,
  package_unit = excluded.package_unit,
  comparison_quantity = excluded.comparison_quantity,
  comparison_unit = excluded.comparison_unit,
  review_status = excluded.review_status,
  quality_notes = excluded.quality_notes,
  default_quantity = excluded.default_quantity,
  unit = excluded.unit,
  image_url = excluded.image_url,
  status = 'active',
  source = excluded.source,
  sort_order = excluded.sort_order,
  updated_at = now();
