'use client'

import { useState } from 'react'
import { comparisonSavings,selectedSupplierCosts } from '@/lib/comparison-savings'
import { comparisonIndicators } from "@/lib/received-product-prices"
import { receivedPriceSummary,requestedSourceTotal } from "@/lib/received-price-summary"
import { buildProductQuotePreview } from "@/lib/product-quote-preview"
import { formatComparisonMoney, type QuoteComparisonItemRecord, type QuoteComparisonBidRecord } from "@/lib/quote-comparison"
import type { ReceivedSupplierQuote } from "@/components/buildflow/received-supplier-quote-table"
import { QuoteMatchReview, SupplierDifferenceWording } from './quote-match-review'

function sourceMoney(value: unknown) {
  return value !== null && value !== undefined && value !== "" && Number.isFinite(Number(value)) ? formatComparisonMoney(Number(value)) : "—"
}
function sourceUnitMoney(value:unknown){
 return value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:4}).format(Number(value)):'—'
}
const legend=[
 {kind:'packaging',label:'Selling units / packaging',color:'bg-blue-600',note:'Confirm package contents before comparing boxes, cartons or individual pieces. No automatic conversion.'},
 {kind:'quantity',label:'Quantity',color:'bg-rose-600',note:'Two pink-red dots: a quantity difference in comparable selling units.'},
 {kind:'measurement',label:'Measurements',color:'bg-red-600',note:'Red: different measurements.'},
 {kind:'alternative',label:'Alternative',color:'bg-orange-500',note:'Orange: alternative material, model or mount; not an approved equivalent.'},
 {kind:'unverified',label:'Not verified',color:'bg-yellow-400',note:'Yellow: manual verification or source allocation is still required.'},
 {kind:'verified',label:'Reviewed',color:'bg-emerald-600',note:'Green: saved manual review. Independent detected differences remain visible.'},
]
type MatrixProps = { items: QuoteComparisonItemRecord[]; quotes: ReceivedSupplierQuote[]; bids: QuoteComparisonBidRecord[]; requestedMaterialLines?:Record<string,string>; selections?:Record<string,string>; onChoose?:(itemId:string,bidId:string)=>void; choiceDisabled?:boolean }
export function ReceivedProductPriceMatrix(props: MatrixProps) { return <InteractivePriceMatrix {...props} /> }
function InteractivePriceMatrix({ items, quotes, bids, requestedMaterialLines = {}, selections={}, onChoose, choiceDisabled=false }: MatrixProps) {
 const [baselineId,setBaselineId]=useState('')
 const [filter,setFilter]=useState('all')
 const reviewed=buildProductQuotePreview(items,bids).rows
 const totals=receivedPriceSummary(items,quotes,bids)
 const savingsView=comparisonSavings(totals,baselineId)
 const selectedCosts=totals.rows.map((row,index)=>{const bid=bids.find(b=>b.id===selections[row.item.id]);return totals.cells[index].find(cell=>cell.quoteId===bid?.source_supplier_quote_id&&cell.verified&&!cell.problem)})
 const selectedTotals=selectedSupplierCosts(totals,bids,selections)
 return <section className="min-w-0" aria-label="Product price comparison">
  <h2 className="mb-2 text-lg font-bold">Compare product prices</h2>
  <div aria-label="Comparison status guide" data-testid="comparison-status-guide" className="mb-3 flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-slate-50 p-3">
   {legend.map(entry=><details key={entry.kind}><summary title={entry.note} className="inline-flex min-h-11 cursor-pointer list-none items-center gap-2 px-3 text-xs focus-visible:outline-2 focus-visible:outline-sky-600"><span aria-hidden="true" className={'h-2.5 w-2.5 rounded-full '+entry.color}/>{entry.kind==='quantity'?<span aria-hidden="true" className={'-ml-1 h-2.5 w-2.5 rounded-full '+entry.color}/>:null}{entry.label}</summary><p className="max-w-64 p-2 text-xs text-slate-600">{entry.note} Click the corresponding dot beside a price to review the request and supplier wording.</p></details>)}
  </div>
  <div className="mb-3 flex flex-wrap items-end gap-3"><label className="grid gap-1 text-xs font-semibold">Compare savings against<select aria-label="Compare savings against" value={baselineId} onChange={event=>setBaselineId(event.target.value)} className="min-h-11 max-w-72 rounded-lg border bg-white px-3"><option value="">Choose supplier</option>{quotes.map(quote=><option key={quote.id} value={quote.id}>{quote.supplierName||quote.fileName}</option>)}</select></label><label className="grid gap-1 text-xs font-semibold">Show<select aria-label="Filter comparison items" value={filter} onChange={event=>setFilter(event.target.value)} className="min-h-11 rounded-lg border bg-white px-3"><option value="all">All items</option><option value="differences">Differences</option><option value="missing">Missing prices</option><option value="selected">Selected</option></select></label></div>
  <p className="mb-3 text-xs text-slate-500">Savings use requested quantities: chosen supplier versus the cheapest comparable offer. Unapproved alternatives and measurement, quantity or allocation conflicts are excluded. Yellow means not manually verified. Materials only; opening or comparing does not approve an order.</p>
  <div className="min-w-0">
  <div className="max-w-full overflow-x-auto rounded-xl border border-slate-200"><table className="w-full text-left text-xs" data-testid="product-price-matrix"><thead className="bg-slate-50"><tr><th className="sticky left-0 z-10 min-w-48 bg-slate-50 p-3">Requested product</th>{quotes.map(quote=><th key={quote.id} className="min-w-32 p-3">{quote.supplierName||quote.fileName}</th>)}<th className="min-w-36 p-3">Savings</th></tr></thead><tbody>
   {totals.rows.map((row,index)=>{
    const result=savingsView.rows[index]
    if(filter==='missing'&&!result.missing||filter==='selected'&&!selectedCosts[index]||filter==='differences'&&!totals.cells[index].some(cell=>cell.problem))return null
    return <tr key={row.item.id} className="border-t border-slate-200 align-top"><th className="sticky left-0 z-10 max-w-72 bg-white p-3 font-normal" ><div data-testid="requested-material-line">{requestedMaterialLines[row.item.id]?<p className="font-semibold">{requestedMaterialLines[row.item.id]}</p>:<><p className="font-bold">{row.item.quantity} {row.item.unit} · {row.item.description}</p><p className="mt-1 text-slate-500">{row.item.specification}</p></>}</div>{onChoose?<label className="mt-3 grid gap-1 text-[10px]">Select supplier<select aria-label={`Select supplier for item ${index+1}`} disabled={choiceDisabled} value={selections[row.item.id]||''} onChange={event=>onChoose(row.item.id,event.target.value)} className="min-h-11 max-w-48 rounded-md border bg-white px-2"><option value="">Not selected</option>{reviewed[index].offers.filter(offer=>offer.eligible&&offer.confirmation).map(offer=><option key={offer.bid.id} value={offer.bid.id}>{offer.bid.supplier_name_snapshot}</option>)}</select><span>Review match before selecting an unverified offer.</span></label>:null}</th>{row.cells.map(cell=>{
     const offer=reviewed[index].offers.find(offer=>offer.bid.source_supplier_quote_id===cell.quote.id)
     const lowest=offer?.eligible&&Boolean(offer.confirmation)&&offer.unitPrice===reviewed[index].lowest?.unitPrice
     const indicators=comparisonIndicators(row.item,cell.lines,cell.reasons).filter(indicator=>indicator.kind!=='unverified'||!offer?.confirmation||indicator.notes.length>1)
     const amounts=totals.cells[index].find(value=>value.quoteId===cell.quote.id)!
     return <td key={cell.quote.id} className={'p-3 '+(lowest?'bg-emerald-50':'')} data-testid="source-product-price">
      <div className="mb-2 flex flex-wrap gap-1">
       {offer?.confirmation?<details data-testid="verified-price-indicator"><summary aria-label="Reviewed" title="Saved manual review" className="inline-flex min-h-11 min-w-11 cursor-pointer list-none items-center justify-center focus-visible:outline-2"><span aria-hidden="true" className="h-2.5 w-2.5 rounded-full bg-emerald-600"/></summary><p className="p-2 text-slate-600">Saved manual review. Detected differences remain shown separately.</p></details>:null}
       {indicators.map(indicator=>{const style=legend.find(entry=>entry.kind===indicator.kind)!;return <details key={indicator.kind} data-kind={indicator.kind} data-testid={indicator.kind==='unverified'?'unverified-price-indicator':'comparison-issue-indicator'}><summary aria-label={style.label} title={indicator.notes.join(' ')} className="inline-flex min-h-11 min-w-11 cursor-pointer list-none items-center justify-center gap-1 focus-visible:outline-2 focus-visible:outline-sky-600 [&::-webkit-details-marker]:hidden"><span aria-hidden="true" className={'h-2.5 w-2.5 rounded-full '+style.color}/>{indicator.kind==='quantity'?<span aria-hidden="true" className={'h-2.5 w-2.5 rounded-full '+style.color}/>:null}</summary><div className="max-w-64 rounded-md bg-slate-50 p-2 text-slate-700"><p>{indicator.notes[0]}</p>{indicator.notes.length>1?<ul aria-label="Comparison checks" className="mt-1 list-disc space-y-1 pl-4">{indicator.notes.slice(1).map(note=><li key={note}>{note}</li>)}</ul>:null}<p className="mt-2 font-semibold">Request: {requestedMaterialLines[row.item.id]||`${row.item.quantity} ${row.item.unit} · ${row.item.description} · ${row.item.specification||''}`}</p>{(cell.lines.length?cell.lines:cell.blockedLines).map(line=><p key={line.allocationKey||line.line_number} className="mt-1">Supplier line {line.line_number}: {line.description} · {line.specification} · {line.originalFeet??line.quantity} {line.calculatedRate!==undefined?'lin. ft.':line.unit}</p>)}<QuoteMatchReview quote={cell.quote} request={requestedMaterialLines[row.item.id]||`${row.item.quantity} ${row.item.unit} · ${row.item.description} · ${row.item.specification||''}`} lines={cell.lines.length?cell.lines:cell.blockedLines} notes={indicators.flatMap(value=>value.notes)} /></div></details>})}
      </div>
      {offer?.eligible&&offer.confirmation?<><p className="text-[10px] text-slate-500">Unit price</p><p className="text-base font-bold">{formatComparisonMoney(offer.unitPrice!)} / {row.item.unit}</p>{amounts.requestedTotal!==null?<p data-testid="requested-line-total" className="mt-2 text-sm font-semibold tabular-nums">Line total: {sourceMoney(amounts.requestedTotal)}<span className="mt-1 block text-[10px] font-normal text-slate-500">{row.item.quantity} {row.item.unit} requested · verified price</span></p>:null}{lowest?<p className="mt-1 text-emerald-800">Lowest verified price</p>:null}</>:cell.lines.length?<>{cell.lines.slice(0,3).map(line=><div key={line.allocationKey||line.line_number} className="mb-2"><p className="text-[10px] text-slate-500">Unit price</p><p className="text-base font-bold tabular-nums">{sourceUnitMoney(line.unit_price)} / {line.unit||'unit'}</p><p data-testid="requested-line-total" className="mt-2 text-sm font-semibold tabular-nums">Line total: {sourceMoney(requestedSourceTotal(row.item,line))}<span className="mt-1 block text-[10px] font-normal text-slate-500">{requestedSourceTotal(row.item,line)===null?'Selling units need review':`${row.item.quantity} ${row.item.unit} × ${sourceUnitMoney(line.unit_price)} · indicative`}</span></p>{line.calculatedRate!==undefined?<p data-testid="linear-foot-calculation" className="mt-1 text-[10px] text-slate-500">Calculated: {sourceMoney(line.calculatedRate)} / lin. ft. × {line.requestedFeet} ft = {sourceMoney(line.line_total)} requested line total. Original quoted footage: {line.originalFeet} ft.</p>:<p className="mt-1 text-[10px] text-slate-500">Quoted: {line.quantity} {line.unit} · {sourceMoney(line.line_total)} line total</p>}<details className="mt-1"><summary className="min-h-8 cursor-pointer text-[10px] text-slate-500">Supplier wording · line {line.line_number}</summary><p className="mt-1 break-words"><SupplierDifferenceWording wording={`${line.description} · ${line.specification||''}`} notes={indicators.flatMap(indicator=>indicator.notes).filter(note=>!note.startsWith('Quantity:'))} /></p></details></div>)}</>:<p className="text-slate-500">{cell.blockedLines.length?'No offer allocated · review quote':'Not available'}</p>}
      <QuoteMatchReview quote={cell.quote} request={requestedMaterialLines[row.item.id]||`${row.item.quantity} ${row.item.unit} · ${row.item.description} · ${row.item.specification||''}`} lines={cell.lines.length?cell.lines:cell.blockedLines} notes={indicators.flatMap(indicator=>indicator.notes)} />
     </td>
    })}<td data-testid="item-savings" className="p-3 tabular-nums"><p className="font-bold">{sourceMoney(result.savings)}</p><dl className="mt-2 space-y-2 text-[10px]"><div><dt>Chosen supplier · line cost</dt><dd>{result.baseline?.requestedTotal!=null?sourceMoney(result.baseline.requestedTotal):baselineId?(result.baseline?.missing?'Not available':'Needs review'):'Choose supplier'}</dd></div><div><dt>Cheapest comparable · line cost</dt><dd>{sourceMoney(result.cheapest?.requestedTotal)}{result.cheapest?<span className="block">{quotes.find(q=>q.id===result.cheapest!.quoteId)?.supplierName}</span>:<span className="block">{result.missing?'Not available':'Needs review'}</span>}</dd></div></dl></td></tr>
   })}
  </tbody></table></div>
  <footer data-testid="comparison-project-totals" className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4">
   <h3 className="font-bold">Request totals</h3>
   <dl className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
    <div><dt className="text-xs text-slate-600">Chosen supplier · materials</dt><dd data-testid="baseline-material-total" className="mt-1 text-xl font-bold tabular-nums">{baselineId?(savingsView.baselineComplete?sourceMoney(savingsView.baselineTotal):'Not available'):'Choose supplier'}</dd><dd className="text-xs text-slate-500">{baselineId?'Some line prices or matches need resolution.':'Choose a supplier above.'}</dd>{baselineId&&!savingsView.baselineComplete?<dd className="mt-1 text-xs text-slate-600">Known-price subtotal: {sourceMoney(savingsView.baselineTotal)} · not the full request cost</dd>:null}</div>
    <div><dt className="text-xs text-slate-600">Cheapest mixed · materials</dt><dd data-testid="cheapest-mixed-total" className="mt-1 text-xl font-bold tabular-nums">{savingsView.cheapestComplete?sourceMoney(savingsView.cheapestTotal):'Not available'}</dd><dd className="text-xs text-slate-500">Comparable offers only · indicative, not an approved order</dd>{!savingsView.cheapestComplete?<dd className="mt-1 text-xs text-slate-600">Comparable-price subtotal: {sourceMoney(savingsView.cheapestTotal)} · unresolved items excluded</dd>:null}</div>
    <div><dt className="text-xs text-slate-600">Savings against chosen supplier</dt><dd data-testid="total-comparison-savings" className="mt-1 text-xl font-bold tabular-nums">{sourceMoney(savingsView.savingsTotal)}</dd><dd className="text-xs text-slate-500">Same {savingsView.comparedCount} comparable item rows only</dd></div>
    <div><dt className="text-xs text-slate-600">Your selected order · materials</dt><dd data-testid="selected-order-total" className="mt-1 text-xl font-bold tabular-nums">{selectedCosts.some(Boolean)?sourceMoney(selectedTotals.materials):'Not selected'}</dd><dd className="text-xs text-slate-500">Reviewed choices · draft, not an order approval</dd></div>
   </dl>
   {savingsView.missingCount?<p className="mt-3 text-sm font-semibold">Missing price: {savingsView.missingCount} items. No supplier provided a matched price.</p>:null}
   {savingsView.reviewCount?<p className="mt-2 text-sm">Needs review: {savingsView.reviewCount} items. Prices may exist, but no comparable offer is ready.</p>:null}
   <details className="mt-4 border-t border-slate-200 pt-2"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Delivery and tax · selected suppliers</summary><p className="text-xs text-slate-500">Separate from material savings. Unknown charges are not $0. Update charges in the existing supplier cost fields.</p>{selectedTotals.suppliers.map((supplier,index)=><dl key={index} className="mt-3 grid gap-2 border-t py-3 text-xs sm:grid-cols-4"><div><dt className="font-bold">{supplier.name}</dt><dd>Materials: {sourceMoney(supplier.materials)}</dd></div><div><dt>Delivery</dt><dd>{supplier.delivery===null?'Not available':sourceMoney(supplier.delivery)}</dd></div><div><dt>Tax</dt><dd>{supplier.tax===null?'Not available':sourceMoney(supplier.tax)}</dd></div><div><dt>Total including charges</dt><dd>{supplier.total===null?'Needs delivery / tax review':sourceMoney(supplier.total)}</dd></div></dl>)}<p className="mt-3 text-sm font-semibold">Selected total including delivery and tax: {selectedTotals.total===null?'Not available':sourceMoney(selectedTotals.total)}</p>{!selectedTotals.selectedCount?<p className="mt-2 text-xs">Select reviewed supplier prices to see delivery and tax.</p>:null}</details>
  </footer></div>
 </section>
}
