'use client'

import { useRef, useState, type CSSProperties } from 'react'
import { comparisonSavings,selectedSupplierCosts,purchasingDraftCosts } from '@/lib/comparison-savings'
import { comparisonIndicators } from "@/lib/received-product-prices"
import { receivedPriceSummary,requestedSourceTotal } from "@/lib/received-price-summary"
import { buildProductQuotePreview } from "@/lib/product-quote-preview"
import { formatComparisonMoney, type QuoteComparisonItemRecord, type QuoteComparisonBidRecord } from "@/lib/quote-comparison"
import type { ReceivedSupplierQuote } from "@/components/buildflow/received-supplier-quote-table"
import { QuoteMatchReview, SupplierDifferenceWording } from './quote-match-review'
import { comparisonQuoteColumns } from '@/lib/comparison-quote-columns'

function sourceMoney(value: unknown) {
  return value !== null && value !== undefined && value !== "" && Number.isFinite(Number(value)) ? formatComparisonMoney(Number(value)) : "—"
}
function sourceUnitMoney(value:unknown){
 return value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:4}).format(Number(value)):'—'
}
const legend=[
 {kind:'packaging',label:'Selling units / packaging',color:'bg-blue-600',note:'Confirm package contents before comparing boxes, cartons or individual pieces. No automatic conversion.'},
 {kind:'quantity',label:'Quantity',color:'bg-rose-600',note:'Two pink-red dots: a quantity difference in comparable selling units.'},
 {kind:'measurement',label:'Measurements',color:'bg-red-600',note:'Red: different measurements.'},
 {kind:'alternative',label:'Alternative',color:'bg-orange-500',note:'Orange: alternative material, model or mount; not an approved equivalent.'},
 {kind:'unverified',label:'Not verified',color:'bg-yellow-400',note:'Yellow: manual verification or source allocation is still required.'},
 {kind:'verified',label:'Reviewed',color:'bg-emerald-600',note:'Green: saved manual review. Independent detected differences remain visible.'},
]
type MatrixProps = { items: QuoteComparisonItemRecord[]; quotes: ReceivedSupplierQuote[]; bids: QuoteComparisonBidRecord[]; requestedMaterialLines?:Record<string,string>; selections?:Record<string,string>; onChoose?:(itemId:string,bidId:string)=>void; choiceDisabled?:boolean; draftSelections?:Record<string,string>; onDraftChoose?:(itemId:string,quoteId:string)=>void; baselineQuoteId?:string; onBaselineChange?:(quoteId:string)=>void; initialSavingsMode?:'mixed'|'selected' }
export function ReceivedProductPriceMatrix(props: MatrixProps) { return <InteractivePriceMatrix {...props} /> }
function InteractivePriceMatrix({ items, quotes:allQuotes, bids, requestedMaterialLines = {}, selections={}, onChoose, choiceDisabled=false,draftSelections:originalDraftSelections={},onDraftChoose,baselineQuoteId,onBaselineChange,initialSavingsMode='selected' }: MatrixProps) {
 const {columns:quotes,aliases}=comparisonQuoteColumns(allQuotes,bids)
 const draftSelections=Object.fromEntries(Object.entries(originalDraftSelections).map(([id,q])=>[id,aliases[q]??q]))
 const [localBaselineId,setLocalBaselineId]=useState('')
 const originalBaselineId=baselineQuoteId??localBaselineId
 const baselineId=aliases[originalBaselineId]??originalBaselineId
 const setBaselineId=onBaselineChange??setLocalBaselineId
 const [filter,setFilter]=useState('all')
 const [savingsMode,setSavingsMode]=useState(initialSavingsMode)
 const matrixScroll=useRef<HTMLDivElement>(null)
 const reviewed=buildProductQuotePreview(items,bids).rows
 const totals=receivedPriceSummary(items,quotes,bids)
 const purchaseChoices=onDraftChoose?draftSelections:undefined
 const savingsView=comparisonSavings(totals,baselineId,savingsMode==='mixed'?undefined:purchaseChoices)
 const selectedView=comparisonSavings(totals,baselineId,purchaseChoices)
 const mixedChoices=Object.fromEntries(savingsView.rows.flatMap((row,index)=>row.cheapest?[[items[index].id,row.cheapest.quoteId]]:[]))
 const selectedCosts=totals.rows.map((row,index)=>{const bid=bids.find(b=>b.id===selections[row.item.id]);return totals.cells[index].find(cell=>cell.quoteId===bid?.source_supplier_quote_id&&cell.verified&&!cell.problem)})
 const selectedTotals=savingsMode==='mixed'?purchasingDraftCosts(totals,bids,mixedChoices):onDraftChoose?purchasingDraftCosts(totals,bids,draftSelections):selectedSupplierCosts(totals,bids,selections)
 const visibleCount=totals.rows.filter((row,index)=>{
  const hasChoice=onDraftChoose?Boolean(draftSelections[row.item.id]):Boolean(selectedCosts[index])
  return !(filter==='missing'&&!savingsView.rows[index].missing||filter==='selected'&&!hasChoice||filter==='unselected'&&hasChoice||filter==='differences'&&!totals.cells[index].some(c=>c.problem))
 }).length
 return <section className="min-w-0" aria-label="Product price comparison">
  <h2 className="mb-2 text-lg font-bold">Compare product prices</h2>
  {allQuotes.length>quotes.length?<p className="mb-2 text-xs text-slate-500">Identical quote entries share one column. All original uploads remain under Original quotes.</p>:null}
  <div aria-label="Comparison status guide" data-testid="comparison-status-guide" className="mb-3 flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-slate-50 p-3">
   {legend.map(entry=><details key={entry.kind}><summary title={entry.note} className="inline-flex min-h-11 cursor-pointer list-none items-center gap-2 px-3 text-xs focus-visible:outline-2 focus-visible:outline-sky-600"><span aria-hidden="true" className={'h-2.5 w-2.5 rounded-full '+entry.color}/>{entry.kind==='quantity'?<span aria-hidden="true" className={'-ml-1 h-2.5 w-2.5 rounded-full '+entry.color}/>:null}{entry.label}</summary><p className="max-w-64 p-2 text-xs text-slate-600">{entry.note} Click the corresponding dot beside a price to review the request and supplier wording.</p></details>)}
  </div>
  <div className="mb-3 flex flex-wrap items-end gap-3"><label className="grid gap-1 text-xs font-semibold">Show<select aria-label="Filter comparison items" value={filter} onChange={event=>setFilter(event.target.value)} className="min-h-11 rounded-lg border bg-white px-3"><option value="all">All items</option><option value="differences">Items with differences</option><option value="missing">No supplier price</option><option value="selected">Items with a supplier chosen</option><option value="unselected">Choose supplier</option></select></label></div>
  <p className="mb-3 text-xs text-slate-500">Select the supplier you want for each item. Savings compare your selected line cost with the supplier in the right-hand Savings header. Cheapest mix calculates the lowest comparable price per item without changing your saved selections. Choices are purchasing drafts, not match verification or order approval. Materials only.</p>
  <p role="status" aria-live="polite" data-testid="comparison-visible-count" className="mb-3 text-xs text-slate-500">Showing {visibleCount} of {items.length} items</p>
  <div className="min-w-0">
  <div className="mb-2 flex flex-wrap items-center gap-2 text-xs"><span className="text-slate-500">All totals are before tax; delivery is separate. On phones, scroll to compare suppliers.</span><button type="button" className="min-h-11 rounded-lg border px-3" onClick={()=>matrixScroll.current?.scrollTo({left:0,behavior:'smooth'})}>Show products / first supplier</button><button type="button" className="min-h-11 rounded-lg border px-3" onClick={()=>matrixScroll.current?.scrollTo({left:matrixScroll.current.scrollWidth,behavior:'smooth'})}>Show Savings / choose supplier</button></div>
  <div ref={matrixScroll} tabIndex={0} role="region" aria-label="Supplier prices and savings, horizontally scrollable" className="max-w-full overflow-x-auto rounded-xl border border-slate-200 focus-visible:outline-2"><table className="w-full min-w-[var(--matrix-width)] table-fixed text-left text-xs min-[1100px]:min-w-0 [&_td]:break-words [&_th]:break-words [&_td]:p-2 [&_th]:p-2 [&_p.text-base]:text-sm" data-testid="product-price-matrix" style={{'--matrix-width':`${400+128*quotes.length}px`,'--supplier-width':`${62/Math.max(quotes.length,1)}%`} as CSSProperties}><colgroup><col className="w-48 min-[1100px]:w-[18%]"/>{quotes.map(quote=><col key={quote.id} className="w-32 min-[1100px]:w-[var(--supplier-width)]"/>)}<col className="w-52 min-[1100px]:w-[20%]"/></colgroup><thead className="bg-slate-50"><tr><th className="bg-slate-50 p-3">Requested product</th>{quotes.map(quote=><th key={quote.id} className="p-3">{quote.supplierName||quote.fileName}</th>)}<th className="sticky right-0 z-20  border-l border-slate-200 bg-slate-50 p-2 shadow-[-3px_0_6px_-4px_rgba(0,0,0,0.25)]">Savings<label className="mt-2 grid gap-1 text-[10px] font-normal">Calculate<select aria-label="Savings calculation mode" value={savingsMode} onChange={event=>setSavingsMode(event.target.value as 'mixed'|'selected')} className="min-h-11 w-full min-w-0 rounded-lg border bg-white px-2"><option value="selected">My selections</option><option value="mixed">Cheapest mix</option></select></label><label className="mt-2 grid gap-1 text-[10px] font-normal">Compare with<select aria-label="Compare savings against" value={baselineId} disabled={choiceDisabled} onChange={event=>setBaselineId(event.target.value)} className="min-h-11 w-full min-w-0 rounded-lg border bg-white px-2"><option value="">Select supplier</option>{quotes.map(quote=><option key={quote.id} value={quote.id}>{quote.supplierName||quote.fileName}</option>)}</select></label></th></tr></thead><tbody>
   {totals.rows.map((row,index)=>{
    const result=savingsView.rows[index]
    const hasChoice=onDraftChoose?Boolean(draftSelections[row.item.id]):Boolean(selectedCosts[index])
    if(filter==='missing'&&!result.missing||filter==='selected'&&!hasChoice||filter==='unselected'&&hasChoice||filter==='differences'&&!totals.cells[index].some(cell=>cell.problem))return null
    return <tr key={row.item.id} className="border-t border-slate-200 align-top"><th className="max-w-72 bg-white p-3 font-normal" ><div data-testid="requested-material-line">{requestedMaterialLines[row.item.id]?<p className="font-semibold">{requestedMaterialLines[row.item.id]}</p>:<><p className="font-bold">{row.item.quantity} {row.item.unit} · {row.item.description}</p><p className="mt-1 text-slate-500">{row.item.specification}</p></>}</div></th>{row.cells.map(cell=>{
     const offer=reviewed[index].offers.find(offer=>offer.bid.source_supplier_quote_id===cell.quote.id)
     const lowest=result.cheapest?.quoteId===cell.quote.id
     const indicators=comparisonIndicators(row.item,cell.lines,cell.reasons).filter(indicator=>indicator.kind!=='unverified'||!offer?.confirmation||indicator.notes.length>1)
     const amounts=totals.cells[index].find(value=>value.quoteId===cell.quote.id)!
     return <td key={cell.quote.id} className={'p-3 '+(lowest?'bg-emerald-50':'')} data-testid="source-product-price">
      <div className="mb-2 flex flex-wrap gap-1">
       {offer?.confirmation?<details data-testid="verified-price-indicator"><summary aria-label="Reviewed" title="Saved manual review" className="inline-flex min-h-11 min-w-11 cursor-pointer list-none items-center justify-center focus-visible:outline-2"><span aria-hidden="true" className="h-2.5 w-2.5 rounded-full bg-emerald-600"/></summary><p className="p-2 text-slate-600">Saved manual review. Detected differences remain shown separately.</p></details>:null}
       {indicators.map(indicator=>{const style=legend.find(entry=>entry.kind===indicator.kind)!;return <details key={indicator.kind} data-kind={indicator.kind} data-testid={indicator.kind==='unverified'?'unverified-price-indicator':'comparison-issue-indicator'}><summary aria-label={style.label} title={indicator.notes.join(' ')} className="inline-flex min-h-11 min-w-11 cursor-pointer list-none items-center justify-center gap-1 focus-visible:outline-2 focus-visible:outline-sky-600 [&::-webkit-details-marker]:hidden"><span aria-hidden="true" className={'h-2.5 w-2.5 rounded-full '+style.color}/>{indicator.kind==='quantity'?<span aria-hidden="true" className={'h-2.5 w-2.5 rounded-full '+style.color}/>:null}</summary><div className="max-w-64 rounded-md bg-slate-50 p-2 text-slate-700"><p>{indicator.notes[0]}</p>{indicator.notes.length>1?<ul aria-label="Comparison checks" className="mt-1 list-disc space-y-1 pl-4">{indicator.notes.slice(1).map(note=><li key={note}>{note}</li>)}</ul>:null}<p className="mt-2 font-semibold">Request: {requestedMaterialLines[row.item.id]||`${row.item.quantity} ${row.item.unit} · ${row.item.description} · ${row.item.specification||''}`}</p>{(cell.lines.length?cell.lines:cell.blockedLines).map(line=><p key={line.allocationKey||line.line_number} className="mt-1">Supplier line {line.line_number}: {line.description} · {line.specification} · {line.originalFeet??line.quantity} {line.calculatedRate!==undefined?'lin. ft.':line.unit}</p>)}<QuoteMatchReview quote={cell.quote} request={requestedMaterialLines[row.item.id]||`${row.item.quantity} ${row.item.unit} · ${row.item.description} · ${row.item.specification||''}`} lines={cell.lines.length?cell.lines:cell.blockedLines} notes={indicators.flatMap(value=>value.notes)} /></div></details>})}
      </div>
      {offer?.eligible&&offer.confirmation?<><p className="text-[10px] text-slate-500">Unit price</p><p className="text-base font-bold">{formatComparisonMoney(offer.unitPrice!)} / {row.item.unit}</p>{amounts.requestedTotal!==null?<p data-testid="requested-line-total" className="mt-2 text-sm font-semibold tabular-nums">Line total: {sourceMoney(amounts.requestedTotal)}<span className="mt-1 block text-[10px] font-normal text-slate-500">{row.item.quantity} {row.item.unit} requested · verified price</span></p>:null}{lowest?<p className="mt-1 text-emerald-800">Lowest verified price</p>:null}</>:cell.lines.length?<>{cell.lines.slice(0,3).map(line=><div key={line.allocationKey||line.line_number} className="mb-2"><p className="text-[10px] text-slate-500">Unit price</p><p className="text-base font-bold tabular-nums">{sourceUnitMoney(line.unit_price)} / {line.unit||'unit'}</p><p data-testid="requested-line-total" className="mt-2 text-sm font-semibold tabular-nums">Line total: {sourceMoney(requestedSourceTotal(row.item,line))}<span className="mt-1 block text-[10px] font-normal text-slate-500">{requestedSourceTotal(row.item,line)===null?'Selling units need review':`${row.item.quantity} ${row.item.unit} × ${sourceUnitMoney(line.unit_price)} · indicative`}</span></p><details data-testid="source-price-details" className="mt-1"><summary className="min-h-8 cursor-pointer text-[10px] text-slate-500">Price details · source line {line.line_number}</summary>{line.calculatedRate!==undefined?<p data-testid="linear-foot-calculation" className="mt-1 text-[10px] text-slate-500">Calculated: {sourceMoney(line.calculatedRate)} / lin. ft. × {line.requestedFeet} ft = {sourceMoney(line.line_total)} requested line total. Original quoted footage: {line.originalFeet} ft.</p>:<p className="mt-1 text-[10px] text-slate-500">Quoted: {line.quantity} {line.unit} · {sourceMoney(line.line_total)} line total</p>}<details className="mt-1"><summary className="min-h-8 cursor-pointer text-[10px] text-slate-500">Supplier wording · line {line.line_number}</summary><p className="mt-1 break-words"><SupplierDifferenceWording wording={`${line.description} · ${line.specification||''}`} notes={indicators.flatMap(indicator=>indicator.notes).filter(note=>!note.startsWith('Quantity:'))} /></p></details></details></div>)}</>:<p className="text-slate-500">{cell.blockedLines.length?'No offer allocated · review quote':'Not available'}</p>}
      <QuoteMatchReview quote={cell.quote} request={requestedMaterialLines[row.item.id]||`${row.item.quantity} ${row.item.unit} · ${row.item.description} · ${row.item.specification||''}`} lines={cell.lines.length?cell.lines:cell.blockedLines} notes={indicators.flatMap(indicator=>indicator.notes)} />
      {lowest?<p data-testid="lowest-comparable-price" className="mt-2 font-semibold text-emerald-800">Lowest comparable price · indicative</p>:null}
     </td>
    })}<td data-testid="item-savings" className="sticky right-0 z-10  border-l border-slate-200 bg-white p-2 tabular-nums shadow-[-3px_0_6px_-4px_rgba(0,0,0,0.25)]">{onDraftChoose?<label className="mb-2 grid gap-1 text-[10px]">Select supplier<select aria-label={`Select supplier for item ${index+1}`} disabled={choiceDisabled} value={draftSelections[row.item.id]||''} onChange={event=>{setSavingsMode('selected');onDraftChoose(row.item.id,event.target.value)}} className="min-h-11 w-full min-w-0 rounded-md border bg-white px-2"><option value="">Select supplier</option>{quotes.map(quote=><option key={quote.id} value={quote.id}>{quote.supplierName||quote.fileName}{totals.cells[index].find(c=>c.quoteId===quote.id)?.missing?' · Not available':''}</option>)}</select></label>:onChoose?<label className="mb-2 grid gap-1 text-[10px]">Select supplier<select aria-label={`Select supplier for item ${index+1}`} disabled={choiceDisabled} value={selections[row.item.id]||''} onChange={event=>onChoose(row.item.id,event.target.value)} className="min-h-11 w-full min-w-0 rounded-md border bg-white px-2"><option value="">Select supplier</option>{reviewed[index].offers.filter(offer=>offer.eligible&&offer.confirmation).map(offer=><option key={offer.bid.id} value={offer.bid.id}>{offer.bid.supplier_name_snapshot}</option>)}</select><span>Review match before selecting an unverified offer.</span></label>:null}<p className={'font-bold '+(result.savings!==null&&result.savings<0?'text-rose-700':'text-emerald-800')}>{result.savings===null?(!baselineId?'Choose comparison supplier':!result.selected?'Choose purchasing supplier':'Needs review'):result.savings<0?`+${sourceMoney(-result.savings)} extra`:`${sourceMoney(result.savings)} savings`}</p><dl className="mt-2 space-y-2 text-[10px]"><div><dt>{savingsMode==='mixed'?'Cheapest mix · line cost':'Selected · line cost'}</dt><dd>{result.selected?.requestedTotal!=null?sourceMoney(result.selected.requestedTotal):result.selected?(result.selected.missing?'Not available':'Needs review'):'Select supplier'}{result.selected?<span className="block">{quotes.find(q=>q.id===result.selected!.quoteId)?.supplierName}</span>:null}</dd></div><div><dt>Compared with · line cost</dt><dd>{result.baseline?.requestedTotal!=null?sourceMoney(result.baseline.requestedTotal):baselineId?(result.baseline?.missing?'Not available':'Needs review'):'Select supplier'}{baselineId?<span className="block">{quotes.find(q=>q.id===baselineId)?.supplierName}</span>:null}</dd></div></dl>{result.savings===null&&result.selected&&baselineId?<p className="mt-2 text-[10px] text-slate-500">Savings need comparable prices and resolved differences.</p>:null}</td></tr>
   })}
  </tbody><tfoot className="border-t-2 border-slate-300 bg-slate-50" data-testid="supplier-column-totals"><tr className="align-top"><th>Materials total<p className="mt-1 text-[10px] font-normal text-slate-500">Entire request · before tax<br/>Delivery excluded</p></th>{totals.suppliers.map((supplier,index)=>{const values=totals.cells.map(row=>row[index]);const unresolved=values.filter(cell=>!cell.indicative||cell.problem).length;return <td key={supplier.quote.id} data-testid="supplier-material-total"><p className="font-bold text-sm tabular-nums">{sourceMoney(supplier.indicativeTotal)}</p><p className="mt-1 text-[10px]">{supplier.pricedCount} of {items.length} items priced</p>{supplier.pricedCount<items.length?<p className="mt-1 font-semibold">Partial · {items.length-supplier.pricedCount} unpriced</p>:null}{unresolved?<p className="mt-1 text-[10px] text-slate-500">{unresolved} matches need review · indicative</p>:<p className="mt-1 text-[10px] text-slate-500">All items comparable · indicative</p>}</td>})}<td className="sticky right-0 z-10 border-l border-slate-200 bg-slate-50" data-testid="savings-mode-total"><p className="font-semibold">{savingsMode==='mixed'?'Cheapest mix':'My selections'}</p><p className="mt-1 text-lg font-bold tabular-nums">{sourceMoney(savingsView.selectedTotal)}</p><p className="mt-1 text-[10px]">Before tax · delivery excluded</p>{!savingsView.selectedComplete?<p className="mt-1 font-semibold">Partial · {items.length-savingsView.rows.filter(row=>row.selected?.indicative&&!row.selected.problem).length} items need selection or review</p>:<p className="mt-1 text-[10px]">All requested items included · indicative</p>}<p className="mt-2 font-bold">{savingsView.savingsTotal===null?'Savings unavailable':savingsView.savingsTotal<0?`+${sourceMoney(-savingsView.savingsTotal)} extra`:`${sourceMoney(savingsView.savingsTotal)} savings`}</p><p className="mt-1 text-[10px]">Against comparison supplier · {savingsView.comparedCount} of {items.length} comparable rows</p></td></tr></tfoot></table></div>
  {totals.rows.every((row,index)=>filter==='missing'&&!savingsView.rows[index].missing||filter==='selected'&&!(onDraftChoose?draftSelections[row.item.id]:selectedCosts[index])||filter==='unselected'&&Boolean(onDraftChoose?draftSelections[row.item.id]:selectedCosts[index])||filter==='differences'&&!totals.cells[index].some(c=>c.problem))?<p role="status" className="mt-3 rounded-lg bg-slate-50 p-3 text-sm">{filter==='missing'?'Every item has a supplier candidate. Some matches may still need review.':filter==='selected'?'No supplier choices yet. Select a supplier for an item, or show All items.':'No items match this filter.'}</p>:null}
  <footer data-testid="comparison-project-totals" className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4">
   <h3 className="font-bold">Request totals</h3>
   <dl className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
    <div><dt className="text-xs text-slate-600">Comparison supplier · materials</dt><dd data-testid="baseline-material-total" className="mt-1 text-xl font-bold tabular-nums">{baselineId?(savingsView.baselineComplete?sourceMoney(savingsView.baselineTotal):'Not available'):'Select supplier'}</dd><dd className="text-xs text-slate-500">{baselineId?(savingsView.baselineComplete?'All requested lines included · indicative':'Some line prices or matches need resolution.'):'Select the comparison supplier in the Savings header.'}</dd>{baselineId&&!savingsView.baselineComplete?<dd className="mt-1 text-xs text-slate-600">Known-price subtotal: {sourceMoney(savingsView.baselineTotal)} · not the full request cost</dd>:null}</div>
    <div><dt className="text-xs text-slate-600">Cheapest mixed · materials</dt><dd data-testid="cheapest-mixed-total" className="mt-1 text-xl font-bold tabular-nums">{savingsView.cheapestComplete?sourceMoney(savingsView.cheapestTotal):'Not available'}</dd><dd className="text-xs text-slate-500">Comparable offers only · indicative, not an approved order</dd>{!savingsView.cheapestComplete?<dd className="mt-1 text-xs text-slate-600">Comparable-price subtotal: {sourceMoney(savingsView.cheapestTotal)} · unresolved items excluded</dd>:null}</div>
    <div><dt className="text-xs text-slate-600">Savings against comparison supplier</dt><dd data-testid="total-comparison-savings" className="mt-1 text-xl font-bold tabular-nums">{savingsView.savingsTotal!==null&&savingsView.savingsTotal<0?`+${sourceMoney(-savingsView.savingsTotal)} extra`:sourceMoney(savingsView.savingsTotal)}</dd><dd className="text-xs text-slate-500">Same {savingsView.comparedCount} comparable item rows only · {onDraftChoose?savingsView.selectedCount:selectedCosts.filter(Boolean).length} of {items.length} items chosen</dd></div>
    <div><dt className="text-xs text-slate-600">Your purchasing draft · materials</dt><dd data-testid="selected-order-total" className="mt-1 text-xl font-bold tabular-nums">{onDraftChoose?(selectedView.selectedCount?(selectedView.selectedComplete?sourceMoney(selectedView.selectedTotal):'Partial'): 'Select supplier'):selectedCosts.some(Boolean)?sourceMoney(selectedTotals.materials):'Select supplier'}</dd>{onDraftChoose&&selectedView.selectedCount&&!selectedView.selectedComplete?<dd className="mt-1 text-xs text-slate-600">Known-price subtotal: {sourceMoney(selectedView.selectedTotal)} · may include unverified choices; not the full request cost</dd>:null}<dd className="text-xs text-slate-500">Draft, not an order approval · delivery and tax excluded</dd></div>
   </dl>
   {savingsView.missingCount?<p className="mt-3 text-sm font-semibold">Missing price: {savingsView.missingCount} items. No supplier provided a matched price.</p>:null}
   {savingsView.reviewCount?<p className="mt-2 text-sm">Needs review: {savingsView.reviewCount} items. Prices may exist, but no comparable offer is ready.</p>:null}
   <details className="mt-4 border-t border-slate-200 pt-2"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Delivery and tax · selected suppliers</summary><p className="text-xs text-slate-500">Separate from material savings. Unknown charges are not $0. Update charges in the existing supplier cost fields.</p>{selectedTotals.suppliers.map((supplier,index)=><dl key={index} className="mt-3 grid gap-2 border-t py-3 text-xs sm:grid-cols-4"><div><dt className="font-bold">{supplier.name}</dt><dd>Materials: {sourceMoney(supplier.materials)}</dd></div><div><dt>Delivery</dt><dd>{supplier.delivery===null?'Not available':sourceMoney(supplier.delivery)}</dd></div><div><dt>Tax</dt><dd>{supplier.tax===null?'Not available':sourceMoney(supplier.tax)}</dd></div><div><dt>Total including charges</dt><dd>{supplier.total===null?'Needs delivery / tax review':sourceMoney(supplier.total)}</dd></div></dl>)}<p className="mt-3 text-sm font-semibold">Selected total including delivery and tax: {selectedTotals.total===null?'Not available':sourceMoney(selectedTotals.total)}</p>{!selectedTotals.selectedCount?<p className="mt-2 text-xs">Select reviewed supplier prices to see delivery and tax.</p>:null}</details>
  </footer></div>
 </section>
}
