"use client"
import { useRef, useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { saveReviewedRequestItemAction } from "@/app/owner/materials/requests/item-edit-actions"
import { recognizeRequestProductLine } from "@/app/owner/materials/requests/row-recognition-actions"
import { requestItemFieldsFromMetadata, type RequestItemField } from "@/lib/request-item-fields"
import type { ReviewableMaterialItem } from "@/lib/client-material-review"
import { materialCleanLine } from "@/lib/material-clean-line"

type Version={item:ReviewableMaterialItem;source:ReviewableMaterialItem|null;revision:string}
const control="min-h-10 w-full min-w-0 rounded-md border border-slate-300 bg-white px-2 text-sm text-slate-950"
function SpreadsheetRow({requestId,version}:{requestId:string;version:Version}){
 const [baseline,setBaseline]=useState(version)
 const {item}=baseline,router=useRouter(),busy=useRef(false)
 const stale=version.revision!==baseline.revision
 const [draft,setDraft]=useState({name:item.name,quantity:String(item.quantity),unit:item.unit||"",details:String(item.metadata?.request_details||""),fields:requestItemFieldsFromMetadata(item.metadata)})
 const [source,setSource]=useState(String(item.metadata?.source_text||""))
 const [recognitionQuestions,setRecognitionQuestions]=useState<string[]>([])
 const [feedback,setFeedback]=useState("")
 const [dirty,setDirty]=useState(false)
 const [pending,startTransition]=useTransition()
 const [proposed,setProposed]=useState<Awaited<ReturnType<typeof recognizeRequestProductLine>>|null>(null)
 const field=(id:string)=>draft.fields.find(f=>f.id===id)?.value||""
 function editField(id:string,label:string,value:string){setDirty(true);setDraft({...draft,fields:[...draft.fields.filter(f=>f.id!==id),...(value?[{id,label,value}]:[])]})}
 const clean=materialCleanLine(draft)
 const proposalClean=proposed?.ok?materialCleanLine({name:proposed.row.name,quantity:proposed.row.quantity??"Quantity needed",unit:proposed.row.unit,details:proposed.row.details,fields:[...draft.fields.filter(f=>!["width","depth","length","model","dimensions","thickness"].includes(f.id)),...([['width',proposed.row.width],['depth',proposed.row.depth],['length',proposed.row.length],['model',proposed.row.model]] as const).filter(([,value])=>value).map(([id,value])=>({id,label:id,value}))]}):null
 function save(){if(busy.current||stale)return;busy.current=true;startTransition(async()=>{try{const result=await saveReviewedRequestItemAction({requestId,itemId:item.id,revision:baseline.revision,edit:{...draft,quantity:Number(draft.quantity),recognitionQuestions}});setFeedback(result.ok?"Saved":result.error);if(result.ok){setBaseline({item:result.item,source:result.source,revision:result.revision});setDirty(false);router.refresh()}}catch{setFeedback("Not saved. Your draft is still here.")}finally{busy.current=false}})}
 function recognize(){if(busy.current||stale)return;busy.current=true;startTransition(async()=>{try{const result=await recognizeRequestProductLine({requestId,itemId:item.id,revision:baseline.revision,text:source});setProposed(result);setFeedback(result.ok?"Proposal ready — compare before applying.":result.error)}catch{setFeedback("Recognition unavailable. Nothing was replaced.")}finally{busy.current=false}})}
 function apply(){if(pending||stale||!proposed?.ok)return;const r=proposed.row;const values:RequestItemField[]=[{id:"width",label:"Width",value:r.width},{id:"depth",label:"Depth / thickness",value:r.depth},{id:"length",label:"Length",value:r.length},{id:"model",label:"Model / SKU",value:r.model}].filter(f=>f.value);setDraft({name:r.name,quantity:r.quantity===null?"":String(r.quantity),unit:r.unit,details:r.details,fields:[...draft.fields.filter(f=>!["width","depth","length","model","dimensions","thickness"].includes(f.id)),...values]});setDirty(true);setRecognitionQuestions(r.questions);setProposed(null);setFeedback("Recognized fields applied. Review and save.")}
 return <tr className="border-t border-slate-200 align-top" data-testid="material-spreadsheet-row"><td className="p-3">{stale?<p role="alert" className="mb-2 text-xs text-amber-800">A newer version is available. Your unsaved draft is retained. Reload after copying any changes you want to keep.</p>:null}<p className="whitespace-pre-wrap text-sm">{String(item.metadata?.source_text||"Source line not captured; open original details.")}</p><details className="mt-2"><summary className="min-h-10 cursor-pointer text-xs text-sky-800">Edit recognition text</summary><textarea disabled={pending} aria-label={`Recognition text for ${item.name}`} value={source} onChange={e=>setSource(e.target.value)} maxLength={3000} className={`${control} min-h-24`} /><p className="text-xs text-slate-500">Original received text stays unchanged.</p></details><button type="button" onClick={recognize} disabled={pending||stale||!source.trim()} className="mt-2 min-h-10 rounded-lg border px-3 text-xs font-semibold disabled:opacity-40">Recognize line</button></td>
 <td className="p-3"><div className="grid grid-cols-2 gap-2"><label className="col-span-2 text-xs">Product<input disabled={pending} className={control} aria-label={`Product ${item.id}`} value={draft.name} onChange={e=>{setDirty(true);setDraft({...draft,name:e.target.value})}} /></label><label className="text-xs">Quantity<input disabled={pending} type="number" min="0.001" step="any" className={control} value={draft.quantity} onChange={e=>{setDirty(true);setDraft({...draft,quantity:e.target.value})}} /></label><label className="text-xs">Unit<input disabled={pending} list="material-unit-options" className={control} value={draft.unit} onChange={e=>{setDirty(true);setDraft({...draft,unit:e.target.value})}} /></label>{([['width','Width'],['depth','Depth / thickness'],['length','Length'],['model','Model / SKU']] as const).map(([id,label])=><label key={id} className="text-xs">{label}<input disabled={pending} list={id==="model"?undefined:`material-${id}-options`} className={control} value={field(id)} placeholder="Not specified" onChange={e=>editField(id,label,e.target.value)} /></label>)}</div><details className="mt-2"><summary className="min-h-10 cursor-pointer text-xs">All details and fields</summary>{draft.fields.filter(f=>!['width','depth','length','model'].includes(f.id)).map(f=><label key={f.id} className="mt-2 block text-xs">{f.label}<input disabled={pending} className={control} value={f.value} onChange={e=>editField(f.id,f.label,e.target.value)} /></label>)}<label className="text-xs">Additional details<textarea disabled={pending} className={control} value={draft.details} onChange={e=>{setDirty(true);setDraft({...draft,details:e.target.value})}} /></label></details></td>
 <td className="p-3">{stale?<p role="alert" className="mb-2 text-xs text-amber-800">A newer version is available. Your unsaved draft is retained. Reload after copying any changes you want to keep.</p>:null}<p className="mb-2 text-xs text-slate-500">{proposed?.ok?'Recognized line · preview':'Current material line'}</p><p data-testid="clean-material-line" className="text-sm">{proposalClean??clean}</p>{proposed?.ok?<div className="mt-3 text-xs"><button type="button" onClick={apply} disabled={pending||stale} className="min-h-10 rounded-lg bg-slate-950 px-3 font-semibold text-white disabled:opacity-40">Use recognized line</button><button type="button" onClick={()=>{setProposed(null);setFeedback('Recognition discarded. Current fields retained.')}} disabled={pending} className="min-h-10 px-2">Discard</button><p className="mt-2 text-slate-500">Use this line to update the fields, then save.</p>{proposed.row.questions.length?<details className="mt-2"><summary className="min-h-10 cursor-pointer text-amber-800">{proposed.row.questions.length} questions to check</summary><ul className="list-disc space-y-2 pl-4">{proposed.row.questions.map((q,i)=><li key={i}>{q}</li>)}</ul></details>:null}</div>:null}<button type="button" disabled={pending||stale||Boolean(proposed?.ok)||!dirty||!draft.name.trim()||!draft.unit.trim()||!Number.isFinite(Number(draft.quantity))||Number(draft.quantity)<=0} onClick={save} className="mt-3 min-h-10 rounded-lg bg-slate-950 px-3 text-xs font-semibold text-white disabled:opacity-40">{pending?'Working…':'Save row'}</button><p role="status" className="mt-2 text-xs text-slate-600">{feedback|| (dirty?'Unsaved changes':'Saved product')}</p>{!proposed?.ok&&recognitionQuestions.length?<details className="mt-2 text-xs"><summary className="min-h-10 cursor-pointer text-amber-800">{recognitionQuestions.length} questions to check</summary><ul className="list-disc space-y-2 pl-4">{recognitionQuestions.map((q,i)=><li key={i}>{q}</li>)}</ul></details>:null}</td></tr>
}
export function RequestMaterialSpreadsheet({requestId,products}:{requestId:string;products:Version[]}){
 const [copy,setCopy]=useState("")
 const editable=products.filter(p=>p.item.metadata?.ai_organized===true)
 return <section aria-label="Material spreadsheet" className="min-w-0 p-3"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-slate-600">Original → structured fields → clean list. Save each changed row before copying.</p><button type="button" className="min-h-10 rounded-lg border px-3 text-xs" onClick={async()=>{try{await navigator.clipboard.writeText(editable.map(({item})=>materialCleanLine({name:item.name,quantity:item.quantity,unit:item.unit||'',fields:requestItemFieldsFromMetadata(item.metadata),details:String(item.metadata?.request_details||'')})).join('\n'));setCopy('Copied saved rows only')}catch{setCopy('Clipboard unavailable. Select the list text to copy.')}}}>Copy saved list</button></div><p role="status" className="text-xs">{copy}</p><datalist id="material-unit-options">{['pieces','sheets','boxes','each','rolls'].map(x=><option key={x} value={x}/>)}</datalist><datalist id="material-depth-options">{['9.5 in','10 in','11.25 in','11.875 in','0.75 in'].map(x=><option key={x} value={x}/>)}</datalist><datalist id="material-length-options">{[10,16,18,20,24,26,28].map(x=><option key={x} value={`${x} ft`}/>)}</datalist><datalist id="material-width-options">{['1.75 in','2 in','2.5 in'].map(x=><option key={x} value={x}/>)}</datalist><div className="max-w-full overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[880px] table-fixed text-left"><thead className="bg-slate-50 text-xs text-slate-600"><tr><th className="w-[28%] p-3">Original source</th><th className="w-[44%] p-3">Product fields</th><th className="p-3">Clean material line</th></tr></thead><tbody>{editable.map(version=><SpreadsheetRow key={version.item.id} requestId={requestId} version={version}/>)}</tbody></table></div></section>
}
