export type AffiliateCallTarget = {
  rank: number;
  company: string;
  phone: string;
  phoneHref: string;
  askFor: string;
  callRoute: string;
  contactLevel: "Dedicated team" | "Direct business" | "Pro or sales team" | "Network managed";
  category: string;
  priority: "A" | "B" | "C";
  programUrl: string;
  programStatus: "Official program" | "Confirm by phone";
  trackerName?: string;
  contactLabel?: string;
  contactHref?: string;
  contactType?: "phone" | "email" | "form";
  contactMethods?: Array<{
    label: string;
    detail: string;
    href: string;
    type: "phone" | "email" | "form";
  }>;
  currentSituation?: string;
  statusLabel?: string;
};

type TargetOptions = Pick<AffiliateCallTarget, "askFor" | "callRoute" | "contactLevel"> & {
  programStatus?: AffiliateCallTarget["programStatus"];
};

const target = (
  rank: number,
  company: string,
  phone: string,
  category: string,
  programUrl: string,
  options: TargetOptions,
): AffiliateCallTarget => ({
  rank,
  company,
  phone,
  phoneHref: `tel:+1${phone.replace(/\D/g, "")}`,
  askFor: options.askFor,
  callRoute: options.callRoute,
  contactLevel: options.contactLevel,
  category,
  priority: rank <= 15 ? "A" : rank <= 35 ? "B" : "C",
  programUrl,
  programStatus: options.programStatus ?? "Official program",
});

const direct = (askFor: string, callRoute: string, programStatus: TargetOptions["programStatus"] = "Official program"): TargetOptions => ({ askFor, callRoute, contactLevel: "Direct business", programStatus });
const team = (askFor: string, callRoute: string, programStatus: TargetOptions["programStatus"] = "Official program"): TargetOptions => ({ askFor, callRoute, contactLevel: "Dedicated team", programStatus });
const sales = (askFor: string, callRoute: string, programStatus: TargetOptions["programStatus"] = "Confirm by phone"): TargetOptions => ({ askFor, callRoute, contactLevel: "Pro or sales team", programStatus });
const network = (askFor: string, callRoute: string): TargetOptions => ({ askFor, callRoute, contactLevel: "Network managed" });

// Public business numbers only. Rankings favor Avantia's active construction departments,
// an official affiliate/referral program, and the fastest publicly documented call route.
export const AFFILIATE_CALL_TARGETS: AffiliateCallTarget[] = [
  target(1, "Concrete Tools Direct", "855-281-1918", "Concrete and masonry tools", "https://concretetoolsdirect.com/pages/join-concrete-tools-direct-affiliate-program", direct("Affiliate program owner", "Say: affiliate application for a construction-material sourcing website")),
  target(2, "Rara RTA Cabinets", "516-979-6789", "Kitchen and bathroom cabinets", "https://www.rarartacabinets.com/create-affiliate-program/", direct("Affiliate or partnerships manager", "Local Long Island line; ask for the in-house affiliate program")),
  target(3, "Tile Club", "833-845-3252", "Tile and surface finishes", "https://www.tileclub.com/pages/affiliate-program", team("Commercial Sales Manager", "Choose Trade Support, extension 2; mention affiliate plus trade referrals")),
  target(4, "Global Industrial", "844-671-1547", "Industrial and jobsite supplies", "https://www.globalindustrial.com/affiliate", team("Reseller Support Team", "Dedicated reseller line; ask about affiliate attribution and product feed")),
  target(5, "KC Tool", "913-440-9766", "Professional tools and business accounts", "https://kctool.com/pages/affiliate-program", team("Business Accounts or affiliate manager", "Ask for B2B first, then the Refersion affiliate owner")),
  target(6, "US Door & More", "813-876-6699", "Interior and exterior doors", "https://www.doornmore.com/partner-program", direct("VIP and affiliate program manager", "Ask for the professional partner program for builders and contractors")),
  target(7, "ADM Flooring", "888-729-6781", "Hardwood flooring", "https://admflooring.com/about-affiliate-program/", direct("Affiliate marketing team", "Ask for the affiliate member program and phone-order attribution")),
  target(8, "HVACDirect", "800-397-1392", "HVAC systems and equipment", "https://hvacdirect.com/affiliates-home", direct("In-house affiliate manager", "Ask sales to transfer you to the affiliate program owner")),
  target(9, "The Tool Nut", "914-621-0200", "Professional power tools", "https://www.toolnut.com/pages/affiliate-program", direct("Affiliate partnerships team", "Local New York line; ask about unique Impact partnership terms")),
  target(10, "Kingston Brass", "877-252-7277", "Plumbing fixtures and faucets", "https://www.kingstonbrass.com/pages/affiliate-program", team("B2B or wholesale inquiries", "Ask for B2B first, then affiliate and trade-program attribution")),
  target(11, "Acme Tools", "877-345-2263", "Professional tools and heavy equipment", "https://www.acmetools.com/affiliates.html", sales("Affiliate partnership contact", "Ask the representative to route an Impact affiliate-program inquiry", "Official program")),
  target(12, "U.S. Electrical Services / LADE", "770-659-7246", "Electrical supplies, wire and lighting", "https://store.ladesupply.com/affiliate", team("Dedicated Affiliate Program Manager", "Online support line; ask for the AvantLink affiliate manager")),
  target(13, "Floor & Decor", "800-631-0958", "Tile, flooring and installation materials", "https://www.flooranddecor.com/pro-premier-rewards-program", team("PRO Customer Care", "Dedicated PRO line; ask about referral attribution and brand partnerships")),
  target(14, "Contractors Direct", "800-709-0002", "Tile, concrete and contractor tools", "https://www.contractorsdirect.com/pages/contact-us", direct("Trade pricing or partnerships manager", "Ask for contractor pricing and a referral partnership", "Confirm by phone")),
  target(15, "Tools4Flooring", "866-634-1189", "Flooring tools and installation supplies", "https://www.tools4flooring.com/contact", direct("Business development or partnerships", "Ask for bulk pricing, product feed, and referral terms", "Confirm by phone")),
  target(16, "Plumbing Deals", "888-682-5956", "Plumbing products and fixtures", "https://plumbing-deals.com/pages/contact-us", direct("Sales or affiliate partnerships", "Ask Mack or Kris for the person handling referral partnerships", "Confirm by phone")),
  target(17, "WinSoon Hardware", "929-391-8558", "Door and barn-door hardware", "https://www.winsoonhardware.com/affiliate/login", direct("In-house affiliate manager", "Ask for the existing affiliate program owner")),
  target(18, "Door Armor", "888-582-2295", "Door security and reinforcement", "https://doorarmor.com/pages/affiliate-program", direct("Affiliate Referral Program", "Ask for the affiliate program managed by iAffiliate Management")),
  target(19, "Specialized Industrial Materials", "281-850-0301", "Concrete repair and specialty materials", "https://www.simaterials.com/products/affiliate/login", direct("Affiliate or business development manager", "Ask for its in-house affiliate account", "Official program")),
  target(20, "IpeDepot", "877-232-3915", "Decking, siding and hardwood", "https://buy.ipedepot.com/pages/affiliates", team("Wholesale or affiliate manager", "Ask for the International & Wholesale division and affiliate terms")),
  target(21, "Ferguson", "888-222-1785", "Plumbing, HVAC and mechanical supplies", "https://www.ferguson.com/content/pro-services/", team("Dedicated phone sales team", "Ask about contractor referrals, account attribution, and a named account rep", "Confirm by phone")),
  target(22, "Lowe's Pro", "844-569-4776", "Building materials and home improvement", "https://www.lowes.com/l/creator/joinlowescreator", team("Pro Service Desk", "Dedicated Pro line; ask for Creator or affiliate-program escalation")),
  target(23, "SupplyHouse", "888-757-4774", "Plumbing, HVAC and electrical", "https://www.supplyhouse.com/", sales("TradeMaster or partnerships manager", "Ask for TradeMaster and referral attribution", "Confirm by phone")),
  target(24, "PlumbersStock", "435-868-4020", "Plumbing and irrigation supplies", "https://www.plumbersstock.com/support/contact.html", direct("Sales partnerships manager", "Ask for contractor, reseller, or referral terms", "Confirm by phone")),
  target(25, "1000Bulbs", "800-624-4488", "Commercial and residential lighting", "https://shop.1000bulbs.com/partnerwithus/", sales("Sales partnership manager", "Ask for partner-with-us and referral attribution", "Confirm by phone")),
  target(26, "BuildDirect", "877-631-2845", "Flooring and building materials", "https://www.builddirect.com/pages/partner-with-us", sales("Partner program manager", "Ask for the partner-with-us team", "Confirm by phone")),
  target(27, "Floor City", "800-898-9540", "Commercial flooring", "https://www.floorcity.com/", sales("Commercial sales or partnerships", "Ask for quote sales and referral attribution", "Confirm by phone")),
  target(28, "Flooring Inc", "800-613-0996", "Residential and commercial flooring", "https://www.flooringinc.com/", sales("Commercial sales or partnerships", "Ask for contractor pricing and referral terms", "Confirm by phone")),
  target(29, "AJ Madison", "800-570-3355", "Appliances and kitchen fixtures", "https://www.ajmadison.com/", team("Corporate Sales", "Choose Sales, then Corporate Sales; ask about referral attribution", "Confirm by phone")),
  target(30, "Factory Buys Direct", "855-607-6557", "Heating and outdoor equipment", "https://www.factorybuysdirect.com/pages/affiliates", direct("In-house affiliate management", "Ask for the AvantLink affiliate owner")),
  target(31, "Wurth Tool", "800-987-8487", "Tools, fasteners and electrical supplies", "https://wurthtool.com/pages/affiliate", direct("Affiliate or business-account manager", "Ask for WurthTool affiliate and business account options")),
  target(32, "MegaDepot", "800-884-5767", "Industrial and safety equipment", "https://ui.awin.com/merchant-profile/89059", network("Awin affiliate-program contact", "Ask sales to identify the employee who owns its Awin program")),
  target(33, "Max Tool", "800-629-3325", "Power tools and equipment", "https://www.maxtool.com/pages/affiliate-program", direct("Affiliate program manager", "Ask for the in-house affiliate contact")),
  target(34, "Toolbarn", "866-597-3850", "Power tools and jobsite equipment", "https://www.toolbarn.com/pages/affiliate-program", direct("Affiliate program manager", "Ask for affiliate and product-feed support")),
  target(35, "Northern Tool + Equipment", "800-221-0516", "Tools, generators and equipment", "https://www.northerntool.com/affiliate-program", network("CJ affiliate-program manager", "Ask for the person responsible for the CJ affiliate program")),
  target(36, "Ohio Power Tool", "800-242-4424", "Professional tools and equipment", "https://ui.awin.com/merchant-profile/89545", network("Awin affiliate-program contact", "Ask for the employee responsible for its Awin program")),
  target(37, "CPO Outlets", "866-577-3014", "New and reconditioned tools", "https://www.cpopowertools.com/outlets-affiliate.html", sales("Affiliate-program owner", "Ask the representative for the affiliate-program contact")),
  target(38, "VEVOR", "888-838-3006", "Tools and construction equipment", "https://ui.awin.com/merchant-profile/28831", network("Awin affiliate-program contact", "Ask for affiliate or creator-program escalation")),
  target(39, "Zoro", "855-289-9676", "Industrial supplies, tools and MRO", "https://www.zoro.com/resellers/", team("Reseller team", "Ask for reseller or referral-program support", "Confirm by phone")),
  target(40, "Rockler", "800-279-4441", "Woodworking tools and hardware", "https://www.rockler.com/", sales("Business development or partnerships", "Ask for referral, creator, or partnership programs", "Confirm by phone")),
  target(41, "Woodcraft", "800-535-4482", "Woodworking tools and supplies", "https://www.woodcraft.com/", sales("Business development or affiliate manager", "Ask for referral or affiliate-program ownership", "Confirm by phone")),
  target(42, "The RTA Store", "877-992-2246", "Kitchen and bathroom cabinets", "https://www.thertastore.com/partner-with-us", sales("Partner program representative", "Ask for the partner-with-us program")),
  target(43, "Cabinets.com", "844-804-7702", "Kitchen cabinets", "https://www.cabinets.com/", sales("Trade or partnerships manager", "Ask for contractor and referral options", "Confirm by phone")),
  target(44, "TileBar", "888-541-3840", "Tile and surface finishes", "https://www.tilebar.com/", sales("Trade sales or partnerships", "Ask for trade referrals and an affiliate option", "Confirm by phone")),
  target(45, "Lumens", "877-445-4486", "Lighting and ceiling fans", "https://www.lumens.com/affiliate-application/", network("Impact affiliate-program manager", "Ask for affiliate-program escalation")),
  target(46, "YLighting", "866-428-9289", "Lighting and ceiling fans", "https://www.ylighting.com/affiliates/", network("Affiliate-program manager", "Ask for the current affiliate contact")),
  target(47, "Build.com / Ferguson Home", "800-375-3403", "Plumbing, lighting and hardware", "https://www.fergusonhome.com/", sales("Trade sales or partnerships", "Ask for professional trade referrals; this is part of Ferguson", "Confirm by phone")),
  target(48, "The Home Depot Pro", "800-466-3337", "Building materials and tools", "https://www.homedepot.com/c/SF_MS_The_Home_Depot_Affiliate_Program", network("Pro or affiliate-program escalation", "No public affiliate extension; request Pro support, then affiliate escalation")),
  target(49, "Ace Hardware", "888-827-4223", "Hardware, paint, tools and plumbing", "https://www.acehardware.com/affiliates", network("Impact affiliate-program manager", "Affiliate support is network-managed; ask for the affiliate escalation path")),
  target(50, "Tractor Supply", "877-718-6750", "Jobsite and outdoor equipment", "https://www.tractorsupply.com/tsc/cms/policies-information/affiliate-program", network("Partnerize affiliate-program manager", "Ask for the person responsible for the Partnerize program")),
];

// The full research list remains available for future work. Carlos's active page is
// intentionally limited to the ten relationships that matter most to AvantiaBuild now.
export const TOP_AFFILIATE_CALL_TARGETS: AffiliateCallTarget[] = [
  {
    rank: 1,
    company: "ABC Supply",
    trackerName: "ABC Supply API / Integration Partnership",
    phone: "800-226-1280",
    phoneHref: "tel:+18002261280",
    contactLabel: "800-226-1280",
    contactHref: "tel:+18002261280",
    contactType: "phone",
    askFor: "myABCsupply support or ABC Connect/API support",
    callRoute: "Mention AvantiaBuild's production-readiness review and ask that the authorized New York account and branch configuration be confirmed.",
    contactLevel: "Dedicated team",
    category: "Roofing, siding, gutters, windows, doors and exterior materials",
    priority: "A",
    programUrl: "https://apidocs.abcsupply.com/api-overview/",
    programStatus: "Official program",
    currentSituation: "Sandbox and certification work are active. Production still depends on an authorized ABC customer account, New York branch access, and a complete account-to-price workflow.",
    contactMethods: [
      { label: "API support", detail: "Official support page", href: "https://apidocs.abcsupply.com/support/", type: "form" },
      { label: "Customer support", detail: "800-226-1280", href: "tel:+18002261280", type: "phone" },
    ],
  },
  {
    rank: 2,
    company: "Lowe's",
    trackerName: "Lowe's Creator",
    phone: "844-569-4776",
    phoneHref: "tel:+18445694776",
    contactLabel: "844-569-4776",
    contactHref: "tel:+18445694776",
    contactType: "phone",
    askFor: "Pro Service Desk, then Creator or developer escalation",
    callRoute: "Wait for the CJ team’s response. Follow up after one week if unanswered.",
    contactLevel: "Dedicated team",
    category: "Building materials, tools, appliances and home improvement",
    priority: "A",
    programUrl: "https://www.cj.com/publisher",
    programStatus: "Official program",
    currentSituation: "Creator Care replied on Aug 31: the social Creator program is not the right fit for a website-only publisher. They referred AvantiaBuild to Lowe's traditional affiliate team at CJ, and that team has been emailed.",
    contactMethods: [
      { label: "Lowe's CJ team", detail: "Allie Smith + 2 contacts", href: "mailto:allie.smith@cj.com?cc=kailie.stevens@cj.com,emily.hausen@cj.com", type: "email" },
      { label: "Pro desk", detail: "844-569-4776", href: "tel:+18445694776", type: "phone" },
      { label: "CJ publisher", detail: "Open publisher application", href: "https://www.cj.com/publisher", type: "form" },
    ],
  },
  {
    rank: 3,
    company: "The Home Depot",
    trackerName: "Home Depot",
    phone: "800-466-3337",
    phoneHref: "tel:+18004663337",
    contactLabel: "800-466-3337",
    contactHref: "tel:+18004663337",
    contactType: "phone",
    askFor: "Pro support or affiliate-program escalation",
    callRoute: "Monitor the Impact application and the Aug 31 support escalation. If no answer arrives, reply to Impact Support with account 7653928 and campaign 8154.",
    contactLevel: "Network managed",
    category: "Building materials, tools, appliances and home improvement",
    priority: "A",
    programUrl: "https://www.homedepot.com/c/SF_MS_The_Home_Depot_Affiliate_Program",
    programStatus: "Official program",
    statusLabel: "Applied — Not Approved",
    currentSituation: "AvantiaBuild’s Impact publisher account 7653928 is approved, but Home Depot requires separate brand approval. Campaign 8154 / brand 1213441 was received Aug 27 and remains under review. Impact Support was emailed Aug 31. There is no separate Home Depot affiliate login.",
    contactMethods: [
      { label: "Impact Support", detail: "publisher.growth@impact.com", href: "mailto:publisher.growth@impact.com", type: "email" },
      { label: "Affiliate page", detail: "Home Depot application", href: "https://www.homedepot.com/c/SF_MS_The_Home_Depot_Affiliate_Program", type: "form" },
      { label: "Customer care", detail: "800-466-3337", href: "tel:+18004663337", type: "phone" },
    ],
  },
  {
    rank: 4,
    company: "Amazon Associates",
    trackerName: "Amazon Associates",
    phone: "Online support",
    phoneHref: "https://affiliate-program.amazon.com/home/contact",
    contactLabel: "Support form",
    contactHref: "https://affiliate-program.amazon.com/home/contact",
    contactType: "form",
    askFor: "Amazon Associates Customer Service",
    callRoute: "Use the Associates contact form for account questions. The immediate goal is three qualifying purchases and completed tax/payment setup.",
    contactLevel: "Dedicated team",
    category: "Tools, hardware, home, appliances and jobsite products",
    priority: "A",
    programUrl: "https://affiliate-program.amazon.com/",
    programStatus: "Official program",
    currentSituation: "The account is active. The Aug 30 dashboard shows 9 clicks, 0 orders and $0 earnings. Amazon still requires the tax interview, payment setup and three qualifying purchases before final account review.",
    contactMethods: [
      { label: "Associates support", detail: "Account contact form", href: "https://affiliate-program.amazon.com/home/contact", type: "form" },
      { label: "Associates Central", detail: "Open account", href: "https://affiliate-program.amazon.com/home", type: "form" },
    ],
  },
  {
    rank: 5,
    company: "Walmart",
    trackerName: "Walmart Affiliate Program",
    phone: "Email support",
    phoneHref: "mailto:affiliates-help-ext@wal-mart.com",
    contactLabel: "Email affiliate team",
    contactHref: "mailto:affiliates-help-ext@wal-mart.com",
    contactType: "email",
    askFor: "Walmart Affiliates Team",
    callRoute: "Wait for Walmart Affiliate Support. The portal may still require an email or phone verification code.",
    contactLevel: "Dedicated team",
    category: "Home improvement, tools, appliances and general merchandise",
    priority: "A",
    programUrl: "https://affiliates.walmart.com/",
    programStatus: "Official program",
    currentSituation: "The website affiliate application was received Aug 17 and is still awaiting a decision. A status follow-up was sent to Walmart Affiliate Support on Aug 31; no decision email is verified yet.",
    contactMethods: [
      { label: "Affiliate support", detail: "affiliates-help-ext@wal-mart.com", href: "mailto:affiliates-help-ext@wal-mart.com", type: "email" },
      { label: "Affiliate portal", detail: "Open application account", href: "https://affiliates.walmart.com/", type: "form" },
    ],
  },
  {
    rank: 6,
    company: "Ferguson Home",
    trackerName: "Ferguson Home",
    phone: "888-222-1785",
    phoneHref: "tel:+18882221785",
    contactLabel: "888-222-1785",
    contactHref: "tel:+18882221785",
    contactType: "phone",
    askFor: "Professional sales or affiliate partnerships",
    callRoute: "Wait for the affiliate team. If unanswered, use Ferguson customer support and professional sales as alternate routes.",
    contactLevel: "Dedicated team",
    category: "Plumbing, HVAC, kitchen, bath and mechanical supplies",
    priority: "A",
    programUrl: "https://www.ferguson.com/content/pro-services/",
    programStatus: "Official program",
    currentSituation: "A direct affiliate inquiry was sent Aug 24 and followed up Aug 31 after Impact approved AvantiaBuild's publisher account. No Ferguson reply is verified yet; customer support and professional sales remain the backup routes.",
    contactMethods: [
      { label: "Affiliate team", detail: "bld-affiliateteam@ferguson.com", href: "mailto:bld-affiliateteam@ferguson.com", type: "email" },
      { label: "Customer support", detail: "customer.support@ferguson.com", href: "mailto:customer.support@ferguson.com", type: "email" },
      { label: "Professional sales", detail: "888-222-1785", href: "tel:+18882221785", type: "phone" },
    ],
  },
  {
    rank: 7,
    company: "Builders FirstSource",
    trackerName: "Builders FirstSource / myBLDR (Trade Account)",
    phone: "844-487-8625",
    phoneHref: "tel:+18444878625",
    contactLabel: "844-487-8625",
    contactHref: "tel:+18444878625",
    contactType: "phone",
    askFor: "Commercial sales, partnerships or a local store manager",
    callRoute: "Reference case 00714195 and request a human contact for Long Island trade purchasing, data access and referrals.",
    contactLevel: "Pro or sales team",
    category: "Lumber, plywood, framing, doors, windows, drywall and components",
    priority: "A",
    programUrl: "https://www.bldr.com/contact/contact-us",
    programStatus: "Confirm by phone",
    currentSituation: "Customer Service was emailed Aug 23, and several online cases produced automated replies, most recently case 00714195 on Aug 25. There is still no verified human partnership or trade-account contact, so the next route is the support line or a local branch.",
    contactMethods: [
      { label: "myBLDR support", detail: "844-487-8625", href: "tel:+18444878625", type: "phone" },
      { label: "Contact form", detail: "Reference case 00714195", href: "https://www.bldr.com/contact/contact-us", type: "form" },
      { label: "Local branch", detail: "Find Long Island location", href: "https://www.bldr.com/locations", type: "form" },
    ],
  },
  {
    rank: 8,
    company: "Ace Hardware",
    trackerName: "Ace Hardware",
    phone: "866-290-5334",
    phoneHref: "tel:+18662905334",
    contactLabel: "866-290-5334",
    contactHref: "tel:+18662905334",
    contactType: "phone",
    askFor: "Impact affiliate-program manager",
    callRoute: "Wait for Ace’s direct campaign link or open the separate Ace campaign inside Impact.",
    contactLevel: "Network managed",
    category: "Hardware, paint, tools, plumbing and local-store products",
    priority: "A",
    programUrl: "https://www.acehardware.com/affiliates",
    programStatus: "Official program",
    currentSituation: "AvantiaBuild's Impact publisher account is approved, but Ace requires its own separate brand application. The Ace affiliate team was followed up on Aug 31 for the direct campaign link; no reply is verified yet.",
    contactMethods: [
      { label: "Affiliate help", detail: "866-290-5334", href: "tel:+18662905334", type: "phone" },
      { label: "Ace application", detail: "Apply to the Ace campaign", href: "https://www.acehardware.com/affiliates", type: "form" },
      { label: "Impact Support", detail: "publisher.growth@impact.com", href: "mailto:publisher.growth@impact.com", type: "email" },
    ],
  },
  {
    rank: 9,
    company: "Acme Tools",
    trackerName: "Acme Tools",
    phone: "877-345-2263",
    phoneHref: "tel:+18773452263",
    contactLabel: "877-345-2263",
    contactHref: "tel:+18773452263",
    contactType: "phone",
    askFor: "Affiliate partnership contact",
    callRoute: "Apply directly to Acme Tools in Impact. If the campaign does not appear, email the Acme affiliate manager with AvantiaBuild's Impact account ID.",
    contactLevel: "Pro or sales team",
    category: "Professional power tools, outdoor equipment and jobsite gear",
    priority: "A",
    programUrl: "https://www.acmetools.com/affiliates.html",
    programStatus: "Official program",
    currentSituation: "No verified Acme application has been submitted yet. Acme publishes a direct Impact application and a named affiliate-manager email.",
    contactMethods: [
      { label: "Affiliate manager", detail: "affiliatesmanager@acmetools.com", href: "mailto:affiliatesmanager@acmetools.com", type: "email" },
      { label: "Impact application", detail: "Apply to Acme Tools", href: "http://app.impact.com/campaign-campaign-info-v2/Acme-Tools.brand", type: "form" },
      { label: "Customer service", detail: "877-345-2263", href: "tel:+18773452263", type: "phone" },
    ],
  },
  {
    rank: 10,
    company: "The RTA Store",
    trackerName: "The RTA Store",
    phone: "877-992-2246",
    phoneHref: "tel:+18779922246",
    contactLabel: "877-992-2246",
    contactHref: "tel:+18779922246",
    contactType: "phone",
    askFor: "Partner-program representative",
    callRoute: "Open the cabinet partner form or call the partner team. Record the application only after a submission confirmation exists.",
    contactLevel: "Pro or sales team",
    category: "Ready-to-assemble kitchen and bathroom cabinets",
    priority: "A",
    programUrl: "https://www.thertastore.com/partner-with-us",
    programStatus: "Official program",
    currentSituation: "The official partner route is identified, but no submitted application or approval is verified.",
    contactMethods: [
      { label: "Partner team", detail: "877-992-2246", href: "tel:+18779922246", type: "phone" },
      { label: "Partner form", detail: "Open partner application", href: "https://www.thertastore.com/partner-with-us", type: "form" },
    ],
  },
];
