import type { ProjectQuoteItemRecord, ProjectQuoteRecord, ProjectRecord } from "@/lib/projects";

type OrderPdfLine = Pick<ProjectQuoteItemRecord, "name" | "quantity" | "unit" | "unit_price" | "line_total">;

export type OrderPdfInput = {
  project: Pick<ProjectRecord, "id" | "name" | "address">;
  quote: Pick<ProjectQuoteRecord, "id" | "subtotal" | "tax" | "total" | "notes">;
  order: {
    id: string;
    createdAt: Date;
    notes: string | null;
  };
  items: OrderPdfLine[];
};

function money(value: number | null | undefined) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Number(value || 0));
}

function cleanPdfText(value: string | null | undefined) {
  return (value || "")
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function escapePdfText(value: string) {
  return cleanPdfText(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapText(value: string, maxLength: number) {
  const words = cleanPdfText(value).split(" ").filter(Boolean);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxLength && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }

  if (current) lines.push(current);
  return lines.length > 0 ? lines : [""];
}

function textLine(x: number, y: number, size: number, text: string) {
  return `BT /F1 ${size} Tf ${x} ${y} Td (${escapePdfText(text)}) Tj ET`;
}

function rect(x: number, y: number, width: number, height: number) {
  return `${x} ${y} ${width} ${height} re S`;
}

function buildPageContent(input: OrderPdfInput) {
  const lines: string[] = [];
  const createdLabel = input.order.createdAt.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  lines.push("0.2 w");
  lines.push(textLine(48, 760, 20, "AVANTIA BUILD"));
  lines.push(textLine(48, 738, 10, "The problem solver for the builder"));
  lines.push(textLine(385, 760, 12, "ORDER PDF"));
  lines.push(textLine(385, 742, 9, `Created ${createdLabel}`));
  lines.push(textLine(385, 727, 9, `Order ${input.order.id.slice(0, 8).toUpperCase()}`));
  lines.push("48 716 500 0 l S");

  lines.push(textLine(48, 690, 12, "Project"));
  lines.push(textLine(48, 672, 10, input.project.name));
  lines.push(textLine(48, 657, 9, input.project.address || "No project address"));
  lines.push(textLine(330, 690, 12, "Quote"));
  lines.push(textLine(330, 672, 10, input.quote.id.slice(0, 8).toUpperCase()));
  lines.push(textLine(330, 657, 9, `Project ${input.project.id.slice(0, 8).toUpperCase()}`));

  lines.push(rect(48, 605, 500, 30));
  lines.push(textLine(58, 623, 9, "Item"));
  lines.push(textLine(338, 623, 9, "Qty"));
  lines.push(textLine(394, 623, 9, "Unit"));
  lines.push(textLine(452, 623, 9, "Line total"));

  let y = 586;
  const visibleItems = input.items.slice(0, 16);

  for (const item of visibleItems) {
    const nameLines = wrapText(item.name, 46).slice(0, 2);
    lines.push(textLine(58, y, 9, nameLines[0]));
    if (nameLines[1]) lines.push(textLine(58, y - 12, 8, nameLines[1]));
    lines.push(textLine(338, y, 9, String(item.quantity ?? "")));
    lines.push(textLine(394, y, 9, item.unit || ""));
    lines.push(textLine(452, y, 9, money(item.line_total)));
    lines.push("48 " + (y - 18) + " 500 0 l S");
    y -= 34;
  }

  if (input.items.length > visibleItems.length) {
    lines.push(textLine(58, y, 9, `${input.items.length - visibleItems.length} more item(s) on the quote record.`));
    y -= 28;
  }

  const totalsY = Math.max(146, y - 10);
  lines.push(textLine(365, totalsY, 10, "Subtotal"));
  lines.push(textLine(452, totalsY, 10, money(input.quote.subtotal)));
  lines.push(textLine(365, totalsY - 18, 10, "Tax / fees"));
  lines.push(textLine(452, totalsY - 18, 10, money(input.quote.tax)));
  lines.push(textLine(365, totalsY - 42, 12, "Total"));
  lines.push(textLine(452, totalsY - 42, 12, money(input.quote.total)));

  const notes = input.order.notes || input.quote.notes;
  if (notes) {
    lines.push(textLine(48, 112, 10, "Notes"));
    for (const [index, noteLine] of wrapText(notes, 90).slice(0, 3).entries()) {
      lines.push(textLine(48, 96 - index * 14, 8, noteLine));
    }
  }

  lines.push(textLine(48, 42, 8, "Generated by Avantia Build and stored with the project documents."));
  return lines.join("\n");
}

export function generateOrderPdf(input: OrderPdfInput) {
  const content = buildPageContent(input);
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  for (const [index, object] of objects.entries()) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  }

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (const offset of offsets.slice(1)) {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, "utf8");
}
