export type ShopNavigationItem = {
  href: string
  label: string
  shortLabel?: string
  description: string
  imageUrl: string
  imageAlt: string
  position?: string
  badge?: string
  disabled?: boolean
}

export const SHOP_SERVICE_LINKS: ShopNavigationItem[] = [
  {
    href: "/beat-a-quote",
    label: "Beat Any Material Quote",
    description: "Send a supplier quote and let Avantia find a better option.",
    imageUrl: "/images/buildflow-retail/orders.jpg",
    imageAlt: "Construction material quote review at a jobsite office",
  },
  {
    href: "/request-quote?request=ai-takeoff",
    label: "Plan Takeoff",
    description: "Upload plans for an AI-assisted material takeoff with expert review.",
    imageUrl: "/images/buildflow-retail/uploads.jpg",
    imageAlt: "Construction plans being reviewed for a material takeoff",
  },
  {
    href: "/request-quote?request=material-list",
    label: "Send Your Material List",
    description: "Paste a list or attach a PDF, photo, or blueprint.",
    imageUrl: "/images/buildflow-retail/projects.jpg",
    imageAlt: "Material list and construction plans prepared for pricing",
  },
  {
    href: "/request-quote?request=custom-item",
    label: "Product Finder",
    description: "Find an exact, uncommon, or hard-to-source construction item.",
    imageUrl: "/images/shop-showroom/professional/product-finder-v1.webp",
    imageAlt: "Construction materials ready for product sourcing",
  },
]

export const SHOP_MATERIAL_LINKS: ShopNavigationItem[] = [
  {
    href: "/shop/framing",
    label: "Frame & Structure",
    shortLabel: "Framing",
    description: "Lumber, plywood, engineered wood, hardware, and fasteners.",
    imageUrl: "/images/buildflow-retail/framing-jobsite-v3.webp",
    imageAlt: "Residential framing jobsite with lumber and sheathing",
  },
  {
    href: "/shop/electrical",
    label: "Power & Electrical",
    shortLabel: "Electrical",
    description: "Wire, cable, panels, boxes, fittings, and rough-in supplies.",
    imageUrl: "/images/buildflow-retail/electrical-department-cutout-v2.webp",
    imageAlt: "Electrical rough-in inside a residential construction project",
    position: "left center",
  },
  {
    href: "/request-quote?request=plumbing",
    label: "Plumbing & Water",
    shortLabel: "Plumbing",
    description: "Pipe, valves, fixtures, drainage, and water-system materials.",
    imageUrl: "/images/materials/photos/plumbing.jpg",
    imageAlt: "Plumbing materials and pipework for residential construction",
    position: "right center",
  },
  {
    href: "/shop/sheet-rock",
    label: "Walls & Drywall",
    shortLabel: "Drywall",
    description: "Board, compound, tape, corner bead, screws, and accessories.",
    imageUrl: "/images/shop-showroom/professional/drywall-installation-v1.webp",
    imageAlt: "Drywall board and finishing materials staged for installation",
    position: "65% center",
  },
  {
    href: "/shop/tile-work",
    label: "Tile & Surfaces",
    shortLabel: "Tile",
    description: "Tile, mortar, grout, waterproofing, backer board, and tools.",
    imageUrl: "/images/buildflow-retail/tile-department-cutout-v2.webp",
    imageAlt: "Tile and surface materials arranged for a residential project",
    position: "left center",
  },
  {
    href: "/shop/wood-floor",
    label: "Flooring",
    description: "Hardwood, engineered wood, vinyl, underlayment, and transitions.",
    imageUrl: "/images/buildflow-retail/flooring-department.webp",
    imageAlt: "Flooring materials prepared for installation",
    position: "center bottom",
  },
  {
    href: "/shop/kitchen",
    label: "Kitchen & Cabinetry",
    shortLabel: "Kitchens",
    description: "Cabinets, layouts, finish packages, and kitchen plan review.",
    imageUrl: "/images/department-essentials/kitchen-grid.webp",
    imageAlt: "Contemporary kitchen cabinetry and finish materials",
    position: "right center",
  },
  {
    href: "/shop/appliances",
    label: "Appliances",
    description: "Builder appliance packages for rentals and residential projects.",
    imageUrl: "/images/materials/photos/appliances.jpg",
    imageAlt: "Residential kitchen appliance package",
    position: "left center",
  },
  {
    href: "/shop/door-and-molding",
    label: "Doors, Trim & Millwork",
    shortLabel: "Doors & Trim",
    description: "Interior doors, jambs, casing, baseboard, crown, and hardware.",
    imageUrl: "/images/buildflow-retail/door-molding-department.webp",
    imageAlt: "Interior doors, trim, molding, and millwork materials",
    position: "35% center",
  },
  {
    href: "/request-quote?request=lighting",
    label: "Lighting",
    description: "Recessed, decorative, task, exterior, and jobsite lighting.",
    imageUrl: "/images/materials/catalog/ele-012.jpg",
    imageAlt: "Architectural lighting installed in a finished interior",
    position: "left top",
  },
  {
    href: "/request-quote?request=insulation",
    label: "Insulation",
    description: "Batt, board, spray-foam accessories, and sound-control products.",
    imageUrl: "/images/materials/photos/insulation.jpg",
    imageAlt: "Residential insulation installation in progress",
    position: "center",
  },
  {
    href: "/shop/siding",
    label: "Siding & Cladding",
    shortLabel: "Siding",
    description: "Siding, panels, trim, starter strips, channels, and fasteners.",
    imageUrl: "/images/buildflow-retail/siding-department-v2.webp",
    imageAlt: "Modern residential siding and exterior cladding materials",
    position: "left center",
  },
  {
    href: "/shop/roofing",
    label: "Roofing",
    description: "Shingles, membranes, flashing, ventilation, and roof accessories.",
    imageUrl: "/images/buildflow-retail/roofing-department.webp",
    imageAlt: "Roofing materials on a residential construction project",
    position: "center top",
  },
  {
    href: "/shop/window",
    label: "Windows & Openings",
    shortLabel: "Windows",
    description: "New-construction and replacement windows with installation supplies.",
    imageUrl: "/images/buildflow-retail/windows-department.webp",
    imageAlt: "Residential windows and opening installation materials",
    position: "70% center",
  },
  {
    href: "/shop/exterior",
    label: "Exterior & Weatherproofing",
    shortLabel: "Exterior",
    description: "Weather barriers, flashing, sealants, exterior trim, and fasteners.",
    imageUrl: "/images/shop-showroom/categories/cinematic-exterior-envelope.webp",
    imageAlt: "Exterior envelope and weatherproofing work on a residence",
    position: "right center",
  },
  {
    href: "/shop/concrete-masonry",
    label: "Concrete & Masonry",
    description: "Concrete, cement, block, mortar, reinforcement, stone, and sand.",
    imageUrl: "/images/shop-showroom/categories/cinematic-concrete-masonry.webp",
    imageAlt: "Concrete and masonry work at an active construction site",
    position: "left center",
  },
  {
    href: "/request-quote?request=tool-rental",
    label: "Tools & Equipment",
    shortLabel: "Tool Rental",
    description: "Reserve specialty tools and equipment for the next job phase.",
    imageUrl: "/images/department-essentials/service-tools-grid.webp",
    imageAlt: "Professional construction tools and equipment at a jobsite",
    position: "right center",
  },
]

export const SHOP_MENU_MATERIAL_LINKS: ShopNavigationItem[] = [
  {
    href: "/shop/framing",
    label: "Frame & Structure",
    description: "Lumber, plywood, framing hardware, and structural material.",
    imageUrl: "/images/buildflow-retail/framing-jobsite-v3.webp",
    imageAlt: "Common framing lumber and structural materials",
  },
  {
    href: "/shop/sheet-rock",
    label: "Walls & Drywall",
    description: "Board, compound, tape, corner bead, screws, and accessories.",
    imageUrl: "/images/buildflow-retail/drywall-department.webp",
    imageAlt: "Drywall board and finishing materials",
  },
  {
    href: "/shop/wood-floor",
    label: "Flooring",
    description: "Hardwood, engineered wood, vinyl, underlayment, and transitions.",
    imageUrl: "/images/buildflow-retail/flooring-department.webp",
    imageAlt: "Flooring planks, underlayment, and installation materials",
  },
  {
    href: "/shop/tile-work",
    label: "Tile & Surfaces",
    description: "Tile, mortar, grout, waterproofing, backer board, and tools.",
    imageUrl: "/images/shop-showroom/professional/tile-installation-v1.webp",
    imageAlt: "Tile and surface installation materials",
  },
  {
    href: "/shop/door-and-molding",
    label: "Doors, Trim & Millwork",
    description: "Doors, jambs, casing, baseboard, crown, and hardware.",
    imageUrl: "/images/buildflow-retail/door-molding-department.webp",
    imageAlt: "Doors, trim, molding, and millwork materials",
  },
  {
    href: "/shop#power-water-comfort",
    label: "Power, Water & Comfort",
    description: "Electrical, plumbing, lighting, and insulation in one place.",
    imageUrl: "/images/shop-showroom/categories/cinematic-rough-in.webp",
    imageAlt: "Electrical and plumbing rough-in materials",
  },
  {
    href: "/shop#kitchen-appliances",
    label: "Kitchen & Appliances",
    description: "Cabinetry, layouts, finish packages, and builder appliances.",
    imageUrl: "/images/shop-showroom/categories/cinematic-kitchen.webp",
    imageAlt: "Kitchen, cabinetry, fixtures, and appliance materials",
  },
  {
    href: "/shop#exterior-envelope",
    label: "Exterior Envelope",
    description: "Roofing, siding, windows, flashing, and weatherproofing.",
    imageUrl: "/images/shop-showroom/categories/cinematic-exterior-envelope.webp",
    imageAlt: "Siding, exterior trim, and weatherproofing materials",
  },
  {
    href: "/shop/concrete-masonry",
    label: "Concrete & Masonry",
    description: "Concrete, cement, block, mortar, reinforcement, stone, and sand.",
    imageUrl: "/images/shop-showroom/categories/cinematic-concrete-masonry.webp",
    imageAlt: "Concrete mix for masonry and structural work",
  },
  {
    href: "/shop?category=Liquidation",
    label: "Deals & Liquidation",
    description: "Surplus, closeout, and limited-quantity construction materials.",
    imageUrl: "/images/shop-showroom/professional/liquidation-materials-v1.webp",
    imageAlt: "Closeout flooring material available for liquidation pricing",
  },
]

export const SHOP_COMING_SOON_LINKS: ShopNavigationItem[] = [
  {
    href: "/ai",
    label: "AI Tools",
    description: "New construction planning and sourcing tools are in development.",
    imageUrl: "/images/buildflow-retail/uploads.jpg",
    imageAlt: "Construction plans being reviewed",
    badge: "Coming soon",
    disabled: true,
  },
  {
    href: "/request-quote?request=delivery-management",
    label: "Jobsite Delivery",
    description: "Expanded live delivery coordination is coming soon.",
    imageUrl: "/images/buildflow-retail/avantia-jobsite-material-delivery-v2.webp",
    imageAlt: "Construction materials arriving at an active jobsite",
    badge: "Coming soon",
    disabled: true,
  },
  {
    href: "/request-quote?request=tool-rental",
    label: "Tools & Equipment",
    description: "Equipment reservations and rental coordination are coming soon.",
    imageUrl: "/images/department-essentials/service-tools-grid.webp",
    imageAlt: "Professional construction tools and equipment",
    badge: "Coming soon",
    disabled: true,
  },
]
