create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron;

create table if not exists public.manager_push_queue (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('new_order', 'call_message', 'supplier_update', 'quote_approval', 'delivery_update', 'test')),
  title text not null,
  body text not null,
  href text not null,
  tag text,
  dedupe_key text not null unique,
  attempts integer not null default 0 check (attempts >= 0),
  available_at timestamptz not null default now(),
  processed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now()
);

create index if not exists manager_push_queue_pending_idx
  on public.manager_push_queue(available_at, created_at)
  where processed_at is null and attempts < 5;

alter table public.manager_push_queue enable row level security;
revoke all on table public.manager_push_queue from anon, authenticated;

do $$
begin
  if not exists (select 1 from vault.secrets where name = 'manager_push_dispatch_secret') then
    perform vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'manager_push_dispatch_secret',
      'Authenticates scheduled Avantia manager push delivery'
    );
  end if;

  if not exists (select 1 from vault.secrets where name = 'project_url') then
    perform vault.create_secret(
      'https://nprfhspwdflpqlopydmp.supabase.co',
      'project_url',
      'Avantia Build Supabase project URL for scheduled Edge Functions'
    );
  end if;
end;
$$;

create or replace function public.get_manager_push_dispatch_secret()
returns text
language sql
security definer
set search_path = ''
stable
as $$
  select decrypted_secret
  from vault.decrypted_secrets
  where name = 'manager_push_dispatch_secret'
  limit 1;
$$;

revoke all on function public.get_manager_push_dispatch_secret() from public, anon, authenticated;
grant execute on function public.get_manager_push_dispatch_secret() to service_role;

create or replace function public.claim_manager_push_events(p_limit integer default 25)
returns table (
  id bigint,
  event_type text,
  title text,
  body text,
  href text,
  tag text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
  with claimed as (
    select queue.id
    from public.manager_push_queue as queue
    where queue.processed_at is null
      and queue.attempts < 5
      and queue.available_at <= now()
    order by queue.created_at
    for update skip locked
    limit least(greatest(coalesce(p_limit, 25), 1), 100)
  ), updated as (
    update public.manager_push_queue as queue
    set attempts = queue.attempts + 1,
        available_at = now() + interval '5 minutes'
    from claimed
    where queue.id = claimed.id
    returning queue.id, queue.event_type, queue.title, queue.body, queue.href, queue.tag
  )
  select updated.id, updated.event_type, updated.title, updated.body, updated.href, updated.tag
  from updated;
end;
$$;

revoke all on function public.claim_manager_push_events(integer) from public, anon, authenticated;
grant execute on function public.claim_manager_push_events(integer) to service_role;

create or replace function public.queue_manager_push_event(
  p_event_type text,
  p_title text,
  p_body text,
  p_href text,
  p_dedupe_key text,
  p_tag text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_event_type not in ('new_order', 'call_message', 'supplier_update', 'quote_approval', 'delivery_update') then
    raise exception 'Unsupported manager push event';
  end if;

  insert into public.manager_push_queue (event_type, title, body, href, dedupe_key, tag)
  values (
    p_event_type,
    left(coalesce(nullif(trim(p_title), ''), 'Avantia update'), 160),
    left(coalesce(nullif(trim(p_body), ''), 'Open Avantia for details.'), 500),
    case when p_href like '/%' then left(p_href, 500) else '/admin/build-map' end,
    left(p_dedupe_key, 240),
    left(p_tag, 120)
  )
  on conflict (dedupe_key) do nothing;
end;
$$;

revoke all on function public.queue_manager_push_event(text, text, text, text, text, text) from public, anon, authenticated;

create or replace function public.queue_new_request_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status <> 'draft' and (tg_op = 'INSERT' or old.status = 'draft') then
    perform public.queue_manager_push_event(
      'new_order',
      'New material request',
      coalesce(new.title, 'A customer submitted a material request.'),
      '/owner/materials/requests/' || new.id::text,
      'new_order:' || new.id::text,
      'avantia-new-order-' || new.id::text
    );
  end if;
  return new;
end;
$$;

drop trigger if exists quote_requests_manager_push on public.quote_requests;
create trigger quote_requests_manager_push
after insert or update of status on public.quote_requests
for each row execute function public.queue_new_request_push();
revoke all on function public.queue_new_request_push() from public, anon, authenticated;

create or replace function public.queue_inbound_communication_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  channel_label text;
begin
  if new.direction <> 'inbound' then return new; end if;
  channel_label := case
    when new.channel = 'call' then 'call'
    when new.channel = 'whatsapp' then 'WhatsApp message'
    when new.channel = 'sms' then 'text message'
    when new.channel = 'email' then 'email'
    else 'message'
  end;
  perform public.queue_manager_push_event(
    'call_message',
    'New ' || channel_label,
    coalesce(nullif(new.summary, ''), nullif(new.body, ''), nullif(new.subject, ''), nullif(new.counterparty_phone, ''), 'Open Messages & Calls for details.'),
    '/admin/communications',
    'call_message:' || new.id::text,
    'avantia-communication-' || new.id::text
  );
  return new;
end;
$$;

drop trigger if exists aura_communications_manager_push on public.aura_communications;
create trigger aura_communications_manager_push
after insert on public.aura_communications
for each row execute function public.queue_inbound_communication_push();
revoke all on function public.queue_inbound_communication_push() from public, anon, authenticated;

create or replace function public.queue_supplier_quote_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.queue_manager_push_event(
    'supplier_update',
    'New supplier quote',
    coalesce(nullif(new.supplier_name, ''), 'A supplier quote was added.'),
    '/admin/supplier-quotes/' || new.id::text,
    'supplier_update:' || new.id::text,
    'avantia-supplier-quote-' || new.id::text
  );
  return new;
end;
$$;

drop trigger if exists supplier_quotes_manager_push on public.supplier_quotes;
create trigger supplier_quotes_manager_push
after insert on public.supplier_quotes
for each row execute function public.queue_supplier_quote_push();
revoke all on function public.queue_supplier_quote_push() from public, anon, authenticated;

create or replace function public.queue_client_approval_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.client_quote_status in ('accepted', 'approved')
    and new.client_quote_status is distinct from old.client_quote_status then
    perform public.queue_manager_push_event(
      'quote_approval',
      'Client approved a quote',
      coalesce(nullif(new.title, ''), nullif(new.quote_number, ''), 'Open the request for details.'),
      '/admin/quote-comparison/' || new.id::text,
      'quote_approval:' || new.id::text || ':' || new.client_quote_status,
      'avantia-quote-approval-' || new.id::text
    );
  end if;
  return new;
end;
$$;

drop trigger if exists quote_comparisons_manager_push on public.quote_comparisons;
create trigger quote_comparisons_manager_push
after update of client_quote_status on public.quote_comparisons
for each row execute function public.queue_client_approval_push();
revoke all on function public.queue_client_approval_push() from public, anon, authenticated;

create or replace function public.dispatch_manager_push_queue()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  project_url text;
  dispatch_secret text;
  request_id bigint;
begin
  if not exists (
    select 1 from public.manager_push_queue
    where processed_at is null and attempts < 5 and available_at <= now()
  ) then return null; end if;

  select decrypted_secret into project_url from vault.decrypted_secrets where name = 'project_url' limit 1;
  select decrypted_secret into dispatch_secret from vault.decrypted_secrets where name = 'manager_push_dispatch_secret' limit 1;
  if project_url is null or dispatch_secret is null then return null; end if;

  select net.http_post(
    url := project_url || '/functions/v1/manager-web-push',
    headers := jsonb_build_object('Content-Type', 'application/json', 'X-Manager-Push-Dispatch', dispatch_secret),
    body := jsonb_build_object('action', 'deliver_queue'),
    timeout_milliseconds := 15000
  ) into request_id;
  return request_id;
end;
$$;

revoke all on function public.dispatch_manager_push_queue() from public, anon, authenticated;

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'dispatch-manager-web-push' limit 1;
  if existing_job is not null then perform cron.unschedule(existing_job); end if;
  perform cron.schedule('dispatch-manager-web-push', '* * * * *', 'select public.dispatch_manager_push_queue();');
end;
$$;
