create table if not exists public.website_defects (
  id uuid primary key default gen_random_uuid(),
  issue_number bigint generated by default as identity unique,
  title text not null check (char_length(trim(title)) between 2 and 160),
  description text not null default '' check (char_length(description) <= 4000),
  page_url text not null default '' check (char_length(page_url) <= 1000),
  status text not null default 'new' check (status in ('new', 'reviewing', 'fixing', 'ready_to_verify', 'resolved')),
  priority text not null default 'normal' check (priority in ('normal', 'high', 'urgent')),
  storage_bucket text not null default 'website-defects' check (storage_bucket = 'website-defects'),
  file_name text not null check (char_length(file_name) between 1 and 240),
  file_path text not null unique check (char_length(file_path) between 10 and 1000),
  mime_type text not null check (mime_type like 'image/%' or mime_type like 'video/%'),
  file_size bigint not null check (file_size between 1 and 104857600),
  assigned_to text not null default 'Codex' check (char_length(assigned_to) between 2 and 80),
  review_notes text not null default '' check (char_length(review_notes) <= 4000),
  created_by uuid not null references auth.users(id) on delete restrict,
  updated_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists website_defects_status_created_idx
  on public.website_defects (status, created_at desc);

create or replace function private.set_website_defects_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_website_defects_updated_at on public.website_defects;
create trigger set_website_defects_updated_at
before update on public.website_defects
for each row execute function private.set_website_defects_updated_at();

alter table public.website_defects enable row level security;
revoke all on table public.website_defects from anon, authenticated;
grant select, insert, update on table public.website_defects to authenticated;
grant usage, select on sequence public.website_defects_issue_number_seq to authenticated;

drop policy if exists website_defects_manager_read on public.website_defects;
create policy website_defects_manager_read
on public.website_defects for select to authenticated
using ((select private.is_admin()) or (select private.is_staff()));

drop policy if exists website_defects_manager_insert on public.website_defects;
create policy website_defects_manager_insert
on public.website_defects for insert to authenticated
with check (
  ((select private.is_admin()) or (select private.is_staff()))
  and created_by = (select auth.uid())
  and updated_by = (select auth.uid())
);

drop policy if exists website_defects_manager_update on public.website_defects;
create policy website_defects_manager_update
on public.website_defects for update to authenticated
using ((select private.is_admin()) or (select private.is_staff()))
with check (
  ((select private.is_admin()) or (select private.is_staff()))
  and created_by is not null
  and updated_by = (select auth.uid())
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'website-defects',
  'website-defects',
  false,
  104857600,
  array['image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/quicktime', 'video/webm']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists website_defect_files_manager_read on storage.objects;
create policy website_defect_files_manager_read on storage.objects
for select to authenticated
using (
  bucket_id = 'website-defects'
  and ((select private.is_admin()) or (select private.is_staff()))
);

drop policy if exists website_defect_files_manager_insert on storage.objects;
create policy website_defect_files_manager_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'website-defects'
  and ((select private.is_admin()) or (select private.is_staff()))
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists website_defect_files_manager_delete on storage.objects;
create policy website_defect_files_manager_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'website-defects'
  and ((select private.is_admin()) or (select private.is_staff()))
);

comment on table public.website_defects is
  'Private manager issue inbox for website screen recordings and screenshots. Each upload is one trackable defect.';

create table if not exists public.website_qa_checks (
  id text primary key check (id ~ '^[a-z0-9-]+$'),
  title text not null check (char_length(trim(title)) between 2 and 160),
  instructions text not null default '' check (char_length(instructions) <= 1000),
  journey_order integer not null default 0,
  last_result text not null default 'not_tested' check (last_result in ('not_tested', 'pass', 'fail', 'blocked')),
  last_notes text not null default '' check (char_length(last_notes) <= 2000),
  last_checked_at timestamptz,
  last_checked_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.website_qa_checks (id, title, instructions, journey_order)
values
  ('client-message', 'Send a message as a client', 'Send a real test message. Confirm it arrives once, opens the right conversation, and the reply is correct.', 10),
  ('request-create', 'Create a client request', 'Create the request from the client message and confirm the client, files, and original text stay attached.', 20),
  ('item-add-organize', 'Add and organize an item', 'Add a product, edit its quantity and description, then reorganize the request and confirm the changes persist.', 30),
  ('supplier-route', 'Add supplier routes', 'Add multiple suppliers in Step 1 and confirm every supplier appears in Step 2.', 40),
  ('supplier-contact', 'Contact suppliers', 'Use phone, message, and email actions. Confirm each action opens the correct supplier and updates its status.', 50),
  ('supplier-quote', 'Upload a supplier quote', 'Upload a quote and confirm only that supplier sees its file, prices, tax, delivery, and lead time.', 60),
  ('price-comparison', 'Compare client and supplier prices', 'Compare line by line without requiring every row. Confirm revenue, profit dollars, and profit percentage.', 70),
  ('proposal-send', 'Create and send a proposal', 'Create the estimate, open its live link, accept the terms, and verify email and text delivery.', 80),
  ('payment-delivery', 'Invoice, payment, receipt, and delivery', 'Create an invoice, send payment instructions, record payment, issue a receipt, and schedule delivery.', 90),
  ('cross-device-sync', 'Verify Carlos live sync', 'Change a request on one computer and confirm Carlos sees it within 10 seconds without a manual refresh.', 100)
on conflict (id) do nothing;

alter table public.website_qa_checks enable row level security;
revoke all on table public.website_qa_checks from anon, authenticated;
grant select, update on table public.website_qa_checks to authenticated;

drop policy if exists website_qa_checks_manager_read on public.website_qa_checks;
create policy website_qa_checks_manager_read
on public.website_qa_checks for select to authenticated
using ((select private.is_admin()) or (select private.is_staff()));

drop policy if exists website_qa_checks_manager_update on public.website_qa_checks;
create policy website_qa_checks_manager_update
on public.website_qa_checks for update to authenticated
using ((select private.is_admin()) or (select private.is_staff()))
with check ((select private.is_admin()) or (select private.is_staff()));

comment on table public.website_qa_checks is
  'Repeatable end-to-end manager QA checklist with the most recent result and timestamp.';
