create table public.aura_request_state_communications (
  id bigint generated by default as identity primary key,
  state_id uuid not null
    references public.aura_sms_request_states(id) on delete cascade,
  communication_id uuid not null
    references public.aura_communications(id) on delete cascade,
  channel text not null check (channel in ('sms', 'whatsapp')),
  direction text not null check (direction in ('incoming', 'outgoing')),
  delivery_status text not null default 'received'
    check (delivery_status in ('received', 'accepted', 'delivered', 'read', 'failed')),
  asked_slots text[] not null default '{}'
    check (cardinality(asked_slots) <= 3),
  answered_slots text[] not null default '{}'
    check (cardinality(answered_slots) <= 3),
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (communication_id)
);

comment on table public.aura_request_state_communications is
  'SMS and WhatsApp communication ledger for one canonical material-request state. Delivery status advances idempotently from provider acceptance to delivered or read.';

create index aura_request_state_communications_state_time_idx
  on public.aura_request_state_communications(state_id, occurred_at desc, id desc);

alter table public.aura_request_state_communications enable row level security;
revoke all on table public.aura_request_state_communications from public, anon, authenticated;
grant all on table public.aura_request_state_communications to service_role;
grant usage, select on sequence public.aura_request_state_communications_id_seq to service_role;
